#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room/partner/candidacy"
ACTION="accept"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# accept with an existing candidacy
# ------------------------------------------------------------------------------
candidacy_id=$(jq -r ".[(($IDX - 1))].id" \
    $TMP/api-pri-room-partner-candidacy-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$candidacy_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
