#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room/partner/candidacy"
ACTION="accept"
TAG="none"

# ------------------------------------------------------------------------------
# accept with a nonexistent candidacy
# ------------------------------------------------------------------------------
candidacy_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$candidacy_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
