#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# add a new room
# ------------------------------------------------------------------------------
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "add" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add an already existing room
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "room" "add" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add a new room for a nonexistent domain
# ------------------------------------------------------------------------------
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "room" "add" "$JSON" 2
