#!/bin/bash
set -e

BASEDIR=$(dirname $0)
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-ok-0)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# new
# ------------------------------------------------------------------------------
name="room-$RANDOM-$(date +'%s')"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)
bash $BASEDIR/../../templates/add-ok "pri" "room" "$JSON" 0

# ------------------------------------------------------------------------------
# exist
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)
bash $BASEDIR/../../templates/add-error "pri" "room" "$JSON" 0

# ------------------------------------------------------------------------------
# for nonexistent domain
# ------------------------------------------------------------------------------
name="room-$RANDOM-$(date +'%s')"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)
bash $BASEDIR/../../templates/add-error "pri" "room" "$JSON" 1
