#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/room/add"
rm -f /tmp/api-pri-room-add-*

cookieJar=$(cat /tmp/kratos-login-cookie)
domain_id=$(jq -r ".[0].id" /tmp/api-pri-domain-add-0)
domain_fake=$(uuidgen)
name="room-$RANDOM-$(date +'%s')"

# ------------------------------------------------------------------------------
# /api/pri/room/add (not exists)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/room/add \
    --output-dir /tmp --output api-pri-room-add-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "domain_id": "$domain_id",
        "name": "$name",
        "has_suffix": true
    }
EOF
res=$(jq . /tmp/api-pri-room-add-0)
out <<< "not exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/room/add (exists)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/room/add \
    --output-dir /tmp --output api-pri-room-add-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "domain_id": "$domain_id",
        "name": "$name",
        "has_suffix": true
    }
EOF
res=$(jq . /tmp/api-pri-room-add-1)
out <<< "exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/room/add (for nonexistent domain)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/room/add \
    --output-dir /tmp --output api-pri-room-add-2 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "domain_id": "$domain_fake",
        "name": "$name",
        "has_suffix": true
    }
EOF
res=$(jq . /tmp/api-pri-room-add-2)
out <<< "for notexistent domain:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/room/add"
