#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add an already existing room
# duplicated (identity_id, domain_id, name)
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].domain_id" $TMP/api-pri-room-get-id-$SET-1-res)
name=$(jq -r ".[0].name" $TMP/api-pri-room-get-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "room" "add" "$JSON" 1
