#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

# ------------------------------------------------------------------------------
# add many new rooms
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)

for i in $(seq 1 $NUM); do
    name="room-$(date +'%s')-$i-$RANDOM"
    JSON=$(cat <<EOF
    {
        "domain_id": "$domain_id",
        "name": "$name",
        "has_suffix": true
    }
EOF
)

    bash $TEMPLATES/action-member-id "pri" "room" "add" "$JSON" $i
done
