#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# room index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# domain index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="room"
ACTION="add-ephemeral"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add many new ephemeral rooms
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-new-id-$ID-$IDX2-res)

JSON=$(cat <<EOF
{
    "domain_id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
