#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# add a new room
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "add" "$JSON" 1
