#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room"
ACTION="add"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing room
# duplicated (identity_id, domain_id, name)
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].domain_id" $TMP/api-pri-room-get-exist-id-$ID-$IDX-res)
name=$(jq -r ".[0].name" $TMP/api-pri-room-get-exist-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
