#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# try to add a new room for a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error "$ID" "pri" "room" "add" "$JSON" 2
