#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room"
ACTION="add"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to add a new room for a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
