#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-1)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# delete an existing room
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "del" "$JSON" 1

# ------------------------------------------------------------------------------
# delete a nonexistent room
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$room_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "room" "del" "$JSON" 1
