#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# delete an existing room
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-1)
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "del" "$JSON" 1
