#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# disable an existing room
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "room" "disable" "id" "$JSON" 1
