#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-0)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# enable an existing room
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "enable" "$JSON" 0

# ------------------------------------------------------------------------------
# enable a nonexistent room
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$room_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "room" "enable" "$JSON" 0
