#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# enable a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$room_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "room" "enable" "$JSON" 1
