#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# enable a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$room_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$ID" "pri" "room" "enable" "$JSON" 1
