#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$room_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room" "get" "$JSON" 1
