#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get for an existing room
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$ID" "pri" "room" "get" "id" "$JSON" 1
