#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get room list (limit 2, offset 1)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2,
    "offset": 1
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "list" "$JSON" 3
