#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-0)
domain_fake=$(uuidgen)
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-0)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": false
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid post
# name is missing in the example
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "domain_id": "$domain_id",
    "has_suffix": false
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "room" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
    {
        "id": "$room_fake",
        "domain_id": "$domain_fake",
        "name": "$name",
        "has_suffix": true
    }
EOF
)

bash $TEMPLATES/action-member-empty "pri" "room" "update" "$JSON" 0
