#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-1)
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": false
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "room" "update" "$JSON" 1
