#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room"
ACTION="update"
TAG="none"

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
domain_fake=$(uuidgen)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$room_fake",
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
