#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
domain_fake=$(uuidgen)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$room_fake",
    "domain_id": "$domain_fake",
    "name": "$name",
    "has_suffix": true
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "room" "update" "$JSON" 1
