#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$SET-1-res)
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-1-res)
name="room-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "domain_id": "$domain_id",
    "name": "$name",
    "has_suffix": false
}
EOF
)

bash $TEMPLATES/action-member-id "$SET" "pri" "room" "update" "$JSON" 1
