#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/room/update"
rm -f /tmp/api-pri-room-update-*

cookieJar=$(cat /tmp/kratos-login-cookie)
domain_id=$(jq -r ".[0].id" /tmp/api-pri-domain-add-0)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# /api/pri/room/update (valid post)
# ------------------------------------------------------------------------------
roomId=$(jq -r .[0].id /tmp/api-pri-room-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/room/update \
    --output-dir /tmp --output api-pri-room-update-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$roomId",
        "domain_id": "$domain_id",
        "name": "myroom",
        "has_suffix": false
    }
EOF
res=$(jq . /tmp/api-pri-room-update-0)
out <<< "valid post:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/room/update (invalid criteria)
# ------------------------------------------------------------------------------
roomId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/room/update \
    --output-dir /tmp --output api-pri-room-update-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$roomId",
        "domain_id": "$domain_fake",
        "name": "myroom",
        "has_suffix": false
    }
EOF
res=$(jq . /tmp/api-pri-room-update-1)
out <<< "invalid criteria:"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/room/update"
