#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/member/candidacy"
ACTION="accept"
TAG="rejected"
ATTR="id"

# ------------------------------------------------------------------------------
# accept a rejected candidacy
# ------------------------------------------------------------------------------
candidacy_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-member-candidacy-reject-exist-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$candidacy_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
