#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/member/candidacy"
ACTION="accept"

# ------------------------------------------------------------------------------
# try to accept with an invalid post (string Id)
# ------------------------------------------------------------------------------
TAG="invalid-string"

profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-new-id-$ID-9-res)
JSON=$(cat <<EOF
{
    "id": "string",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to reject with an invalid post (numeric Id)
# ------------------------------------------------------------------------------
TAG="invalid-number"

profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-new-id-$ID-9-res)
JSON=$(cat <<EOF
{
    "id": 987,
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to reject with an invalid post (fake profile)
# ------------------------------------------------------------------------------
TAG="invalid-profile"

candidacy_id=$(jq -r ".[2].id" \
    $TMP/api-pri-meeting-member-candidacy-list-nolimit-nooffset-id-$ID-1-res)
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$candidacy_id",
    "profile_id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
