#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/member/candidacy"
ACTION="accept"
TAG="none"

# ------------------------------------------------------------------------------
# accept with a nonexistent candidacy
# ------------------------------------------------------------------------------
candidacy_fake=$(uuidgen)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-new-id-$ID-9-res)
JSON=$(cat <<EOF
{
    "id": "$candidacy_fake",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
