#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1)
meeting_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# get for an existing meeting
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-guest-id "pub" "meeting" "get" "$JSON" 1

# ------------------------------------------------------------------------------
# get for a nonexistent meeting
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-guest-empty "pub" "meeting" "get" "$JSON" 1
