#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && IDX=1 || IDX=$1

SERVICE="pub"
CLASS="meeting"
ACTION="get"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get for an existing meeting
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-1-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-guest-attr $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
