#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get for an existing meeting
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-guest-id "pub" "meeting" "get" "$JSON" 1
