#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && IDX=1 || IDX=$1

SERVICE="pub"
CLASS="meeting"
ACTION="get"
TAG="none"

# ------------------------------------------------------------------------------
# get for a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-guest-empty $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
