#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && IDX=1 || IDX=$1

SERVICE="pub"
CLASS="meeting"
ACTION="get/link/bycode"
TAG="exist"
ATTR="url"

# ------------------------------------------------------------------------------
# get bycode for an existing meeting
# ------------------------------------------------------------------------------
code=$(jq -r ".[0].code" \
    $TMP/api-pri-meeting-invite-get-exist-host-audience-of-permanent-id-1-$IDX-res)
JSON=$(cat <<EOF
{
    "code": "$code"
}
EOF
)

bash $TEMPLATES/action-guest-attr $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
