#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get public meeting list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-guest-empty "pub" "meeting" "list" "$JSON" 1
