#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get enabled meeting list (no limit, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-guest-id "pub" "meeting" "list/enabled" "$JSON" 1

# ------------------------------------------------------------------------------
# get enabled meeting list (limit 2, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-guest-id "pub" "meeting" "list/enabled" "$JSON" 2

# ------------------------------------------------------------------------------
# get enabled meeting list (limit 2, offset 1)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2,
    "offset": 1
}
EOF
)

bash $TEMPLATES/action-guest-id "pub" "meeting" "list/enabled" "$JSON" 3

# ------------------------------------------------------------------------------
# get enabled meeting list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-guest-empty "pub" "meeting" "list/enabled" "$JSON" 1

# ------------------------------------------------------------------------------
# get enabled meeting list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-guest-error "pub" "meeting" "list/enabled" "$JSON" 1
