#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && IDX=1 || IDX=$1

SERVICE="pub"
CLASS="meeting"
ACTION="list"
TAG="huge-offset"

# ------------------------------------------------------------------------------
# get public meeting list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-guest-empty $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
