#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new invites for members (for 2. meeting)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-2-res)
invite_type="member"

affiliation="host"
disposable=true
for i in $(seq 1 $NUM); do
    JSON=$(cat <<EOF
    {
        "meeting_id": "$meeting_id",
        "name": "invite-$RANDOM",
        "invite_type": "$invite_type",
        "affiliation": "$affiliation",
        "disposable": $disposable
    }
EOF
)
    [[ "$affiliation" = "host" ]] && affiliation="guest" || affiliation="host"
    [[ "$affiliation" = "host" ]] && disposable=true || disposable=false

    bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" "add" \
        "id" "$JSON" $i
done
