#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# invite
[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX1=1 || IDX1=$2
# meeting
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="meeting/invite"
ACTION="add"
TAG="new-host-member-of-permanent"
ATTR="id"

# ------------------------------------------------------------------------------
# add new invite for host member of permanent meeting
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-$ID-$IDX2-res)
join_as="host"
invite_to="member"
disposable=true
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "name": "invite-$RANDOM",
    "invite_to": "$invite_to",
    "join_as": "$join_as",
    "disposable": $disposable
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX1
