#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/invite"
ACTION="add"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to add a new invite for a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_fake",
    "name": "invite-$RANDOM",
    "invite_to": "audience",
    "join_as": "guest",
    "disposable": false
}
EOF
)
bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
