#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new invites for members
# ------------------------------------------------------------------------------
invite_type="member"

join_as="host"
disposable=true
for i in $(seq 1 $NUM); do
    meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-$i-res)
    JSON=$(cat <<EOF
    {
        "meeting_id": "$meeting_id",
        "name": "invite-$RANDOM",
        "invite_type": "$invite_type",
        "join_as": "$join_as",
        "disposable": $disposable
    }
EOF
)
    [[ "$join_as" = "host" ]] && join_as="guest" || join_as="host"
    [[ "$join_as" = "host" ]] && disposable=true || disposable=false

    bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" "add" \
        "id" "$JSON" $i
done
