#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new invites
# ------------------------------------------------------------------------------
as_host=true
disposable=true
for i in $(seq 1 $NUM); do
    meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-$i-res)
    JSON=$(cat <<EOF
    {
        "meeting_id": "$meeting_id",
        "name": "invite-$RANDOM",
        "as_host": $as_host,
        "disposable": $disposable
    }
EOF
)
    [[ "$as_host" = false ]] && as_host=true || as_host=false
    disposable=$as_host

    bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" "add" \
        "id" "$JSON" $i
done
