#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new invite for a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_fake",
    "name": "invite-$RANDOM",
    "invite_to": "audience",
    "join_as": "guest",
    "disposable": false
}
EOF
)
bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/invite" "add" \
    "$JSON" 1
