#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/invite"
ACTION="get"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get for an existing invite
# ------------------------------------------------------------------------------
invite_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-invite-add-new-host-member-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
