#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/invite"
ACTION="get/bycode"
TAG="exist"
ATTR="meeting_name"

# ------------------------------------------------------------------------------
# get by code for an existing invite
# ------------------------------------------------------------------------------
invite_code=$(jq -r ".[0].code" \
    $TMP/api-pri-meeting-invite-get-exist-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
