#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get by code for an existing invite
# ------------------------------------------------------------------------------
invite_code=$(jq -r ".[0].code" $TMP/api-pri-meeting-invite-get-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" "get/bycode" \
    "meeting_name" "$JSON" 1
