#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for an existing invite
# ------------------------------------------------------------------------------
invite_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-invite-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" "get" "id" \
    "$JSON" 1
