#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/invite"
ACTION="list/bymeeting"
TAG="permanent-huge-offset"

# ------------------------------------------------------------------------------
# get the invite list of the permanent meeting (no limit, offset 1000000)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
