#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get invite list (limit 2, no offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-1-res)
echo $meeting_id
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/invite" \
    "list/bymeeting" "id" "$JSON" 2
