#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get invite list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/invite" \
    "list/bymeeting" "$JSON" 1
