#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# add a new profile
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "add" "$JSON" 0

# ------------------------------------------------------------------------------
# try to add an already existing profile
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "add" "$JSON" 0

# ------------------------------------------------------------------------------
# try to add a new profile without an email field
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "name": "$name"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "add" "$JSON" 1
