#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="profile"
ACTION="add"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing profile
# duplicated (identity_id, name, email)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-profile-get-exist-id-$ID-1-res)
email=$(jq -r ".[0].email" $TMP/api-pri-profile-get-exist-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
