#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add an already existing profile
# duplicated (identity_id, name, email)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-profile-get-id-$SET-1-res)
email=$(jq -r ".[0].email" $TMP/api-pri-profile-get-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "profile" "add" "$JSON" 1
