#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="profile"
ACTION="add"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new profile
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$IDX-$RANDOM"
email="profile-$IDX@mydomain.com"
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
