#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new profile without an email field
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "name": "$name"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "profile" "add" "$JSON" 2
