#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to add an already existing profile
# duplicated (identity_id, name, email)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-profile-get-id-1)
email=$(jq -r ".[0].email" $TMP/api-pri-profile-get-id-1)
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "add" "$JSON" 1
