#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# add a new profile
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
email="$name@mydomain.com"
JSON=$(cat <<EOF
{
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "add" "$JSON" 1
