#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

# ------------------------------------------------------------------------------
# add many new profiles
# ------------------------------------------------------------------------------
for i in $(seq 1 $NUM); do
    name="profile-$(date +'%s')-$i-$RANDOM"
    email="profile-$i@mydomain.com"
    JSON=$(cat <<EOF
    {
        "name": "$name",
        "email": "$email"
    }
EOF
)

    bash $TEMPLATES/action-member-id "pri" "profile" "add" "$JSON" $i
done
