#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="profile"
ACTION="add"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to add a new profile without an email field
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "name": "$name"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
