#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# delete an existing profile
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "profile" "del" "id" "$JSON" 1
