#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-0)
profile_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# enable an existing profile
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "enable" "$JSON" 0

# ------------------------------------------------------------------------------
# enable a nonexistent profile
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "profile" "enable" "$JSON" 0
