#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get for an existing profile
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "profile" "get" "$JSON" 1
