#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for a nonexistent profile
# ------------------------------------------------------------------------------
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "profile" "get" "$JSON" 1
