#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get default profile
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "profile" "get/default" "$JSON" 1
