#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get profile list (limit 2, offset 1)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2,
    "offset": 1
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "profile" "list" "id" "$JSON" 3
