#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get profile list (limit 2, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "profile" "list" "$JSON" 2
