#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get profile list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "list" "$JSON" 1
