#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get enabled profile list (no limit, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "list/enabled" "$JSON" 0

# ------------------------------------------------------------------------------
# get enabled profile list (limit 2, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "list/enabled" "$JSON" 1

# ------------------------------------------------------------------------------
# get enabled profile list (limit 2, offset 1)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2,
    "offset": 1
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "list/enabled" "$JSON" 2

# ------------------------------------------------------------------------------
# get enabled profile list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "profile" "list/enabled" "$JSON" 0

# ------------------------------------------------------------------------------
# get enabled profile list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "list/enabled" "$JSON" 0
