#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
{
    "id": "$profile_id",
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "profile" "update" "id" \
    "$JSON" 1
