#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to update with invalid post
# email is missing in the example
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1)
name="profile-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$profile_id",
    "name": "$name"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "update" "$JSON" 1
