#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="profile"
ACTION="update"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-new-id-$ID-$IDX-res)
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
{
    "id": "$profile_id",
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
