#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update a nonexistent profile
# ------------------------------------------------------------------------------
profile_fake=$(uuidgen)
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
{
    "id": "$profile_fake",
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "profile" "update" "$JSON" 1
