#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-0)
profile_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
{
    "id": "$profile_id",
    "name": "$name",
    "email": "$email"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "profile" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid post
# email is missing in the example
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$profile_id",
    "name": "$name"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "profile" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
name="profile-$(date +'%s')-$RANDOM"
email="myprofile@mydomain.com"
JSON=$(cat <<EOF
    {
        "id": "$profile_fake",
        "name": "$name",
        "email": "$email"
    }
EOF
)

bash $TEMPLATES/action-member-empty "pri" "profile" "update" "$JSON" 0
