#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new schedule for a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_fake"
    "name": "name-$RANDOM",
    "started_at": "$(date -d "+1 hours" --iso-8601=minutes)",
    "duration": 30
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/schedule" "add" \
    "$JSON" 1
