#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="del"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# delete an existing schedule
# ------------------------------------------------------------------------------
schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
