#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# delete a nonexistent schedule
# ------------------------------------------------------------------------------
schedule_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$schedule_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting/schedule" "del" \
    "$JSON" 1
