#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# delete an existing schedule
# ------------------------------------------------------------------------------
schedule_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-schedule-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/schedule" "del" "id" \
    "$JSON" 1
