#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# member
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="get/bymembership"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get bymembership for an existing schedule
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-membership-add-bycode-new-host-member-of-scheduled-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
