#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get schedule list (no limit, no offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[1].id" $TMP/api-pri-meeting-list-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/schedule" \
    "list/bymeeting" "id" "$JSON" 1
