#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="list/bymeeting"
TAG="invalid"

# ------------------------------------------------------------------------------
# get schedule list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-scheduled-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
