#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="update"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
    "duration": 30
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
