#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid post
# minus duration
# ------------------------------------------------------------------------------
schedule_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-schedule-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
    "duration": -30
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/schedule" "update" \
    "$JSON" 1
