#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
schedule_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-schedule-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
    "duration": 30
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/schedule" "update" \
    "id" "$JSON" 1
