#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="update"

# ------------------------------------------------------------------------------
# try to update with invalid json.
# duration should be string but number here.
# ------------------------------------------------------------------------------
TAG="invalid-json"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": 30
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to update with invalid post
# duration should be more than 0
# ------------------------------------------------------------------------------
TAG="invalid-once-duration-0"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "0"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (once) with invalid duration
# duration should be less than 1440
# ------------------------------------------------------------------------------
TAG="invalid-once-duration-1500"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "1500"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (once) with invalid date
# it is already over
# ------------------------------------------------------------------------------
TAG="invalid-once-over"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "-1 hours" --iso-8601=minutes)",
      "duration": "30"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid duration
# duration should be more than 0
# ------------------------------------------------------------------------------
TAG="invalid-daily-duration-0"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "0",
      "rep_end_type": "x",
      "rep_end_x": "10",
      "rep_every": "2"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid duration
# duration should be less than 1440
# ------------------------------------------------------------------------------
TAG="invalid-daily-duration-1500"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "1500",
      "rep_end_type": "x",
      "rep_end_x": "10",
      "rep_every": "2"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid date
# it is already over
# ------------------------------------------------------------------------------
TAG="invalid-daily-over"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "-20 days" --iso-8601=minutes)",
      "duration": "30",
      "rep_end_type": "x",
      "rep_end_x": "10",
      "rep_every": "2"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid rep type
# rep_end_type should be "x" for daily
# ------------------------------------------------------------------------------
TAG="invalid-daily-rep-type"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "30",
      "rep_end_type": "FAKE",
      "rep_end_x": "10",
      "rep_every": "2"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid end_x
# rep_end_x should be less than 100
# ------------------------------------------------------------------------------
TAG="invalid-daily-end-x"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "30",
      "rep_end_type": "x",
      "rep_end_x": "100",
      "rep_every": "2"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (daily) with invalid rep_every
# rep_every should be less than 31
# ------------------------------------------------------------------------------
TAG="invalid-daily-rep-every"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "d",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "30",
      "rep_end_type": "x",
      "rep_end_x": "10",
      "rep_every": "50"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid duration
# duration should be more than 0
# ------------------------------------------------------------------------------
TAG="invalid-weekly-duration-0"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "0",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "1",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid duration
# duration should be less than 1440
# ------------------------------------------------------------------------------
TAG="invalid-weekly-duration-1500"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "1500",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "1",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid date
# it is already over
# ------------------------------------------------------------------------------
TAG="invalid-weekly-over"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "-8 days" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "-4 days" --iso-8601=minutes)",
      "rep_every": "1",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep type
# rep_end_type should be "at" for weekly
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-type"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "FAKE",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "1",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid end_at
# end_at should be later than started_at
# ------------------------------------------------------------------------------
TAG="invalid-weekly-end-at"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 days" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+2 days" --iso-8601=minutes)",
      "rep_every": "1",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep_every
# rep_every should be less than 31
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-every"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "50",
      "rep_days": "0010100"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep_days
# rep_days should be '[01]{7}'
# invalid character in this example
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-days-1"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "2",
      "rep_days": "0010102"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep_days
# rep_days should be '[01]{7}'
# longer string
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-days-2"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "2",
      "rep_days": "0010101010101"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep_days
# rep_days should be '[01]{7}'
# shorter string
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-days-3"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "2",
      "rep_days": "001"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new schedule (weekly) with invalid rep_days
# rep_days should be '[01]{7}'
# no selected day, all 0
# ------------------------------------------------------------------------------
TAG="invalid-weekly-rep-days-4"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)

JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "w",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "20",
      "rep_end_type": "at",
      "rep_end_at": "$(date -d "+90 days" --iso-8601=minutes)",
      "rep_every": "2",
      "rep_days": "0000000"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
