#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update nonexistent schedule
# ------------------------------------------------------------------------------
schedule_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$schedule_fake",
    "name": "name-$RANDOM",
    "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
    "duration": 30
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting/schedule" "update" \
    "$JSON" 1
