#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/schedule"
ACTION="update"

# ------------------------------------------------------------------------------
# try to update with invalid post
# minus duration
# ------------------------------------------------------------------------------
TAG="invalid-range"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-once-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": "-30"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to update with invalid json.
# duration should be string but number here.
# ------------------------------------------------------------------------------
TAG="invalid-json"

schedule_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-schedule-add-new-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$schedule_id",
    "name": "name-$RANDOM",
    "schedule_attr": {
      "type": "o",
      "started_at": "$(date -d "+3 hours" --iso-8601=minutes)",
      "duration": 30
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
