#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the request owner id
[[ -z "$1" ]] && SET1=2 || SET1=$1
# the meeting owner id
[[ -z "$2" ]] && SET2=1 || SET2=$2
[[ -z "$3" ]] && NUM=1 || NUM=$3

# ------------------------------------------------------------------------------
# add many new requests
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET1-1-res)

for i in $(seq 1 $NUM); do
    meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET2-$i-res)
    JSON=$(cat <<EOF
    {
        "profile_id": "$profile_id",
        "meeting_id": "$meeting_id"
    }
EOF
)

    bash $TEMPLATES/action-member-id "$SET1" "pri" "request" "add" "$JSON" $i
done
