#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to add an already existing request
# duplicated (identity_id, meeting_id)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].meeting_id" $TMP/api-pri-request-get-id-1-res)
profile_id=$(jq -r ".[0].profile_id" $TMP/api-pri-request-get-id-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "request" "add" "$JSON" 1
