#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# try to add a request for already existing membership
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].profile_id" $TMP/api-pri-request-get-id-$ID-1-res)
meeting_id=$(jq -r ".[0].meeting_id" \
    $TMP/api-pri-membership-add-byinvite-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-error "$ID" "pri" "request" "add" "$JSON" 2
