#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new requests
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$ID-1-res)

for i in $(seq 1 $NUM); do
    meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$ID-$i-res)
    JSON=$(cat <<EOF
    {
        "profile_id": "$profile_id",
        "meeting_id": "$meeting_id"
    }
EOF
)

    bash $TEMPLATES/action-member-id "$ID" "pri" "request" "add" "$JSON" $i
done
