#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get for an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-request-add-id-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "request" "get" "$JSON" 1
