#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get for an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-request-add-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "request" "get" "$JSON" 1
