#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# get request list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "$ID" "pri" "request" "list" "$JSON" 1
