#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the meeting owner id
[[ -z "$1" ]] && ID1=1 || ID1=$1
# the request owner id
[[ -z "$2" ]] && ID2=2 || ID2=$2

# ------------------------------------------------------------------------------
# reject an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-request-add-id-$ID2-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-id "$ID1" "pri" "request" "reject" "$JSON" 1
