#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-request-add-id-$ID-1-res)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "request" "update" "$JSON" 1
