#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
request_fake=$(uuidgen)
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_fake",
    "profile_id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "request" "update" "$JSON" 1
