#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/scripts/common

# ------------------------------------------------------------------------------
# kratos
# ------------------------------------------------------------------------------
bash $BASEDIR/scripts/kratos/registration
bash $BASEDIR/scripts/kratos/login

# ------------------------------------------------------------------------------
# adm
# ------------------------------------------------------------------------------
bash $BASEDIR/scripts/adm/hello

# ------------------------------------------------------------------------------
# pri
# ------------------------------------------------------------------------------
bash $BASEDIR/scripts/pri/hello

# profile
bash $BASEDIR/scripts/pri/profile/add-nonexist
bash $BASEDIR/scripts/pri/profile/get-exist
bash $BASEDIR/scripts/pri/profile/get-nonexist
bash $BASEDIR/scripts/pri/profile/get-default
bash $BASEDIR/scripts/pri/profile/add-exist
bash $BASEDIR/scripts/pri/profile/add-invalid-post

bash $BASEDIR/scripts/pri/profile/update-exist
bash $BASEDIR/scripts/pri/profile/update-nonexist
bash $BASEDIR/scripts/pri/profile/update-invalid-post
bash $BASEDIR/scripts/pri/profile/del-exist
bash $BASEDIR/scripts/pri/profile/del-nonexist

bash $BASEDIR/scripts/pri/profile/add-many 10
bash $BASEDIR/scripts/pri/profile/set-default-exist
bash $BASEDIR/scripts/pri/profile/set-default-nonexist
bash $BASEDIR/scripts/pri/profile/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/profile/list-limit
bash $BASEDIR/scripts/pri/profile/list-limit-offset
bash $BASEDIR/scripts/pri/profile/list-huge-offset
bash $BASEDIR/scripts/pri/profile/list-invalid-post

# domain
bash $BASEDIR/scripts/pri/domain/add-nonexist
bash $BASEDIR/scripts/pri/domain/get-exist
bash $BASEDIR/scripts/pri/domain/get-nonexist
bash $BASEDIR/scripts/pri/domain/add-exist
bash $BASEDIR/scripts/pri/domain/add-invalid-post

bash $BASEDIR/scripts/pri/domain/update-exist
bash $BASEDIR/scripts/pri/domain/update-nonexist
bash $BASEDIR/scripts/pri/domain/update-invalid-post
bash $BASEDIR/scripts/pri/domain/disable-exist
bash $BASEDIR/scripts/pri/domain/disable-nonexist
bash $BASEDIR/scripts/pri/domain/enable-exist
bash $BASEDIR/scripts/pri/domain/enable-nonexist
bash $BASEDIR/scripts/pri/domain/del-exist
bash $BASEDIR/scripts/pri/domain/del-nonexist

bash $BASEDIR/scripts/pri/domain/add-many 10
bash $BASEDIR/scripts/pri/domain/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/domain/list-limit
bash $BASEDIR/scripts/pri/domain/list-limit-offset
bash $BASEDIR/scripts/pri/domain/list-huge-offset
bash $BASEDIR/scripts/pri/domain/list-invalid-post

# room
bash $BASEDIR/scripts/pri/room/add-nonexist
bash $BASEDIR/scripts/pri/room/get-exist
bash $BASEDIR/scripts/pri/room/get-nonexist
bash $BASEDIR/scripts/pri/room/add-exist
bash $BASEDIR/scripts/pri/room/add-invalid-post

bash $BASEDIR/scripts/pri/room/update-exist
bash $BASEDIR/scripts/pri/room/update-nonexist
bash $BASEDIR/scripts/pri/room/update-invalid-post
bash $BASEDIR/scripts/pri/room/disable-exist
bash $BASEDIR/scripts/pri/room/disable-nonexist
bash $BASEDIR/scripts/pri/room/enable-exist
bash $BASEDIR/scripts/pri/room/enable-nonexist
bash $BASEDIR/scripts/pri/room/del-exist
bash $BASEDIR/scripts/pri/room/del-nonexist

bash $BASEDIR/scripts/pri/room/add-many 10
bash $BASEDIR/scripts/pri/room/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/room/list-limit
bash $BASEDIR/scripts/pri/room/list-limit-offset
bash $BASEDIR/scripts/pri/room/list-huge-offset
bash $BASEDIR/scripts/pri/room/list-invalid-post

# meeting
bash $BASEDIR/scripts/pri/meeting/add-nonexist
bash $BASEDIR/scripts/pri/meeting/get-exist
bash $BASEDIR/scripts/pri/meeting/get-nonexist
bash $BASEDIR/scripts/pri/meeting/add-invalid-post

bash $BASEDIR/scripts/pri/meeting/update-exist
bash $BASEDIR/scripts/pri/meeting/update-nonexist
bash $BASEDIR/scripts/pri/meeting/update-invalid-post
bash $BASEDIR/scripts/pri/meeting/disable-exist
bash $BASEDIR/scripts/pri/meeting/disable-nonexist
bash $BASEDIR/scripts/pri/meeting/enable-exist
bash $BASEDIR/scripts/pri/meeting/enable-nonexist
bash $BASEDIR/scripts/pri/meeting/del-exist
bash $BASEDIR/scripts/pri/meeting/del-nonexist

bash $BASEDIR/scripts/pri/meeting/add-many 10
bash $BASEDIR/scripts/pri/meeting/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/meeting/list-limit
bash $BASEDIR/scripts/pri/meeting/list-limit-offset
bash $BASEDIR/scripts/pri/meeting/list-huge-offset
bash $BASEDIR/scripts/pri/meeting/list-invalid-post

# invite
bash $BASEDIR/scripts/pri/invite/add-nonexist
bash $BASEDIR/scripts/pri/invite/get-exist
bash $BASEDIR/scripts/pri/invite/get-nonexist
bash $BASEDIR/scripts/pri/invite/add-invalid-post

bash $BASEDIR/scripts/pri/invite/disable-exist
bash $BASEDIR/scripts/pri/invite/disable-nonexist
bash $BASEDIR/scripts/pri/invite/enable-exist
bash $BASEDIR/scripts/pri/invite/enable-nonexist
bash $BASEDIR/scripts/pri/invite/del-exist
bash $BASEDIR/scripts/pri/invite/del-nonexist

bash $BASEDIR/scripts/pri/invite/add-many 10
bash $BASEDIR/scripts/pri/invite/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/invite/list-limit
bash $BASEDIR/scripts/pri/invite/list-limit-offset
bash $BASEDIR/scripts/pri/invite/list-huge-offset
bash $BASEDIR/scripts/pri/invite/list-invalid-post

# membership
bash $BASEDIR/scripts/pri/membership/add-byinvite-nonexist
bash $BASEDIR/scripts/pri/membership/get-exist
bash $BASEDIR/scripts/pri/membership/get-nonexist
bash $BASEDIR/scripts/pri/membership/add-byinvite-exist
bash $BASEDIR/scripts/pri/membership/add-byinvite-invalid-post

bash $BASEDIR/scripts/pri/membership/update-exist
bash $BASEDIR/scripts/pri/membership/update-nonexist
bash $BASEDIR/scripts/pri/membership/del-exist
bash $BASEDIR/scripts/pri/membership/del-nonexist

bash $BASEDIR/scripts/pri/membership/add-byinvite-many 10
bash $BASEDIR/scripts/pri/membership/list-nolimit-nooffset
bash $BASEDIR/scripts/pri/membership/list-limit
bash $BASEDIR/scripts/pri/membership/list-limit-offset
bash $BASEDIR/scripts/pri/membership/list-huge-offset
bash $BASEDIR/scripts/pri/membership/list-invalid-post

# ------------------------------------------------------------------------------
# pub
# ------------------------------------------------------------------------------
bash $BASEDIR/scripts/pub/hello

# domain
bash $BASEDIR/scripts/pub/domain/list-enabled

# meeting
bash $BASEDIR/scripts/pub/meeting/get
bash $BASEDIR/scripts/pub/meeting/list-enabled

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< completed successfully
