#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the room owner id
[[ -z "$1" ]] && ID1=1 || ID1=$1
# the partner id
[[ -z "$2" ]] && ID2=2 || ID2=$2
[[ -z "$3" ]] && IDX=1 || IDX=$3

SERVICE="pri"
CLASS="room/partner"
ACTION="enable"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# enable an existing partner
# ------------------------------------------------------------------------------
partner_id=$(jq -r ".[0].id" \
                 $TMP/api-pri-room-partnership-add-bycode-new-id-$ID2-1-res)
JSON=$(cat <<EOF
{
    "id": "$partner_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
