#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the room owner
[[ -z "$1" ]] && ID1=1 || ID1=$1
[[ -z "$2" ]] && IDX1=1 || IDX1=$2
# the partner
[[ -z "$3" ]] && ID2=2 || ID2=$3
[[ -z "$4" ]] && IDX2=1 || IDX2=$4

SERVICE="pri"
CLASS="room/partner"
ACTION="enable"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# enable an existing partner
# ------------------------------------------------------------------------------
partner_id=$(jq -r ".[0].id" \
    $TMP/api-pri-room-partnership-add-bycode-new-id-$ID2-$IDX2-res)
JSON=$(cat <<EOF
{
    "id": "$partner_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX1
