#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get partner list (limit 1, no offset)
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "room/partner" "list/byroom" \
    "id" "$JSON" 1
