#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# this script needs the registration to be completed successfully
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

header <<< "kratos login"
rm -f $TMP/kratos-login-*
rm -f $TMP/*.kratos.login

# ------------------------------------------------------------------------------
# kratos login flow
# ------------------------------------------------------------------------------
cookieJar=$(mktemp -p $TMP --suffix .kratos.login)
echo $cookieJar >$TMP/kratos-login-cookie

curl -ks https://$KRATOS_FQDN/self-service/login/browser \
    --output-dir $TMP --output kratos-login-flow \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
actionUrl=$(jq -r .ui.action $TMP/kratos-login-flow)
csrfToken=$(jq -r \
    '.ui.nodes[] | select(.attributes.name=="csrf_token") | .attributes.value' \
    $TMP/kratos-login-flow)

out <<< "flow, action URL:"
out <<< "  $actionUrl"
out <<< "login flow, CSRF token:"
out <<< "  $csrfToken"

# ------------------------------------------------------------------------------
# kratos credential
# ------------------------------------------------------------------------------
email=$(grep email $TMP/kratos-credential | cut -d= -f2)
passwd=$(grep passwd $TMP/kratos-credential | cut -d= -f2)

out <<< "email:"
out <<< "  $email"
out <<< "passwd:"
out <<< "  $passwd"

# ------------------------------------------------------------------------------
# kratos login
# ------------------------------------------------------------------------------
cookieJar=$(cat $TMP/kratos-login-cookie)

curl -ks -X POST "$actionUrl" \
    --output-dir $TMP --output kratos-login-session \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "csrf_token": "$csrfToken",
        "password_identifier": "$email",
        "password": "$passwd",
        "method": "password"
    }
EOF
userId=$(jq -r .session.identity.id $TMP/kratos-login-session)
[[ -z "$userId" ]] && exit 1
[[ "$userId" = "null" ]] && exit 1

out <<< "user id:"
out <<< "  $userId"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "kratos login"
