#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

header <<< "kratos registration"
rm -f /tmp/kratos-credential
rm -f /tmp/kratos-registration-*
rm -f /tmp/*.kratos.registration

# ------------------------------------------------------------------------------
# kratos registration flow
# ------------------------------------------------------------------------------
cookieJar=$(mktemp --suffix .kratos.registration)
echo $cookieJar >/tmp/kratos-registration-cookie

curl -ks https://$KRATOS_FQDN/self-service/registration/browser \
    --output-dir /tmp --output kratos-registration-flow \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
actionUrl=$(jq -r .ui.action /tmp/kratos-registration-flow)
csrfToken=$(jq -r \
    '.ui.nodes[] | select(.attributes.name=="csrf_token") | .attributes.value' \
    /tmp/kratos-registration-flow)

out <<< "flow, action URL:"
out <<< "  $actionUrl"
out <<< "flow, CSRF token:"
out <<< "  $csrfToken"

# ------------------------------------------------------------------------------
# kratos registration
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-registration-cookie)
email=user.$(date +%s)@galaxy.corp
passwd=$(openssl rand -base64 12)

curl -ks -X POST "$actionUrl" \
    --output-dir /tmp --output kratos-registration-session \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "csrf_token": "$csrfToken",
        "traits.email": "$email",
        "password": "$passwd",
        "method": "password"
    }
EOF
userId=$(jq -r .identity.id /tmp/kratos-registration-session)
[[ "$userId" = "null" ]] && exit 1

echo "email=$email" >/tmp/kratos-credential
echo "passwd=$passwd" >>/tmp/kratos-credential

out <<< "user id:"
out <<< "  $userId"
out <<< "email:"
out <<< "  $email"
out <<< "passwd:"
out <<< "  $passwd"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "kratos registration"
