#!/usr/bin/bash
set -e

# ------------------------------------------------------------------------------
# Run this script as api user. Stop api services before running this script:
#
#   systemctl stop galaxy-api-pub.service
#   systemctl stop galaxy-api-pri.service
#   systemctl stop galaxy-api-adm.service
# ------------------------------------------------------------------------------

REMOTE="https://github.com/emrahcom/galaxy.git"
[[ -n "$BRANCH" ]] || BRANCH="main"
LOCAL="/tmp/galaxy"
API="$LOCAL/machines/eb-app-api/home/api"
APP="$API/galaxy"

# get DB_PASSWD
[[ -z "$DB_PASSWD" ]] && \
    DB_PASSWD=$(ack "^export const DB_PASSWD =" \
        /home/api/galaxy/config.ts | cut -d'"' -f2)
if [[ -z "$DB_PASSWD" ]]; then
    echo "error: DB_PASSWD is not found"
    exit 1
else
    echo "DB_PASSWD: $DB_PASSWD"
fi

# get GALAXY_FQDN
[[ -z "$GALAXY_FQDN" ]] && \
    GALAXY_FQDN=$(ack "^export const GALAXY_FQDN =" \
        /home/api/galaxy/config.ts | cut -d'"' -f2)
if [[ -z "$GALAXY_FQDN" ]]; then
    echo "error: GALAXY_FQDN is not found"
    exit 1
else
    echo "GALAXY_FQDN: $GALAXY_FQDN"
fi

# get KRATOS_FQDN
[[ -z "$KRATOS_FQDN" ]] && \
    KRATOS_FQDN=$(ack "^export const KRATOS_FQDN =" \
        /home/api/galaxy/config.ts | cut -d'"' -f2)
if [[ -z "$KRATOS_FQDN" ]]; then
    echo "error: KRATOS_FQDN is not found"
    exit 1
else
    echo "KRATOS_FQDN: $KRATOS_FQDN"
fi

# get the mailer config
cp /home/api/galaxy/config.mailer.ts /tmp/

# clone
cat <<EOF

BRANCH: $BRANCH

EOF

rm -rf $LOCAL
git clone --depth=1 --branch $BRANCH $REMOTE $LOCAL

sed -i \
  -e "s~___DB_PASSWD___~$DB_PASSWD~" \
  -e "s~___GALAXY_FQDN___~$GALAXY_FQDN~" \
  -e "s~___KRATOS_FQDN___~$KRATOS_FQDN~" \
  $APP/config.ts
cp /tmp/config.mailer.ts $APP/
cat $APP/config.ts
cat $APP/config.mailer.ts

# upgrade app
rm -rf /tmp/galaxy.old
mv /home/api/galaxy /tmp/galaxy.old
cp -arp $APP /home/api/

# clear cache
rm -rf /home/api/.cache/deno

# upgrade this script
cp $API/upgrade-galaxy /home/api/

# reminder
cat <<EOF

Dont forget to clear caches. Run as root:

  rm -rf /home/api-adm/.cache/deno
  rm -rf /home/api-pri/.cache/deno
  rm -rf /home/api-pub/.cache/deno

  reboot
EOF
