#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pub started"
rm -f /tmp/api-public-*

# ------------------------------------------------------------------------------
# /api/pub/hello
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pub/hello \
    --output-dir /tmp --output api-public-hello \
    -H "Accept: application/json"
res=$(jq -r .text /tmp/api-public-hello)
[[ "$res" = "null" ]] && exit 1

out <<< "/api/pub/hello"
out <<< "  $res"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pub completed"
