#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# this script needs the registration to be completed successfully
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pri started"
rm -f /tmp/api-private-*
rm -f /tmp/kratos-login-*
rm -f /tmp/*.kratos.login

# ------------------------------------------------------------------------------
# /api/pri/hello (no authentication)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/hello \
    --output-dir /tmp --output api-private-hello \
    -H "Accept: application/json"
res=$(jq -r .text /tmp/api-private-hello)
[[ "$res" != "hello null" ]] && exit 1

out <<< "/api/pri/hello (no authentication)"
out <<< "  $res"

# ------------------------------------------------------------------------------
# kratos login flow
# ------------------------------------------------------------------------------
cookieJar=$(mktemp --suffix .kratos.login)

curl -ks https://$KRATOS_FQDN/self-service/login/browser \
    --output-dir /tmp --output kratos-login-flow \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
actionUrl=$(jq -r .ui.action /tmp/kratos-login-flow)
csrfToken=$(jq -r \
    '.ui.nodes[] | select(.attributes.name=="csrf_token") | .attributes.value' \
    /tmp/kratos-login-flow)

out <<< "kratos login flow, action URL:"
out <<< "  $actionUrl"
out <<< "kratos login flow, CSRF token:"
out <<< "  $csrfToken"

# ------------------------------------------------------------------------------
# kratos credential
# ------------------------------------------------------------------------------
email=$(grep email /tmp/kratos-credential | cut -d= -f2)
passwd=$(grep passwd /tmp/kratos-credential | cut -d= -f2)

out <<< "kratos credential, email:"
out <<< "  $email"
out <<< "kratos credential, passwd:"
out <<< "  $passwd"

# ------------------------------------------------------------------------------
# kratos login
# ------------------------------------------------------------------------------
curl -ks -X POST "$actionUrl" \
    --output-dir /tmp --output kratos-login-session \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "csrf_token": "$csrfToken",
        "password_identifier": "$email",
        "password": "$passwd",
        "method": "password"
    }
EOF
userId=$(jq -r .session.identity.id /tmp/kratos-login-session)
[[ "$userId" = "null" ]] && exit 1

out <<< "kratos login, user id:"
out <<< "  $userId"

# ------------------------------------------------------------------------------
# /api/pri/hello (with authentication)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/hello \
    --output-dir /tmp --output api-private-hello \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
res=$(jq -r .text /tmp/api-private-hello)
[[ "$res" = "hello null" ]] && exit 1

out <<< "/api/pri/hello (with authentication):"
out <<< "  $res"

# ------------------------------------------------------------------------------
# /api/pri/domain/add
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/add \
    --output-dir /tmp --output api-private-domain-add-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "name": "jitsi.mydomain.corp",
        "auth_type": "none",
        "attributes": {
        }
    }
EOF
res=$(jq -r .domainId /tmp/api-private-domain-add-0)
[[ "$res" = "null" ]] && exit 1

out <<< "/api/pri/domain/add domain id:"
out <<< "  $res"

# ------------------------------------------------------------------------------
# /api/pri/domain/add (already exists)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/add \
    --output-dir /tmp --output api-private-domain-add-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "name": "jitsi.mydomain.corp",
        "auth_type": "none",
        "attributes": {
        }
    }
EOF
res=$(jq -r .domainId /tmp/api-private-domain-add-1)
[[ "$res" != "null" ]] && exit 1

out <<< "/api/pri/domain/add (already exists) domain id:"
out <<< "  $res"

# ------------------------------------------------------------------------------
# /api/pri/domain/del
# ------------------------------------------------------------------------------
domain_id=$(jq -r .domainId /tmp/api-private-domain-add-0)
curl -ks -X POST https://$APP_FQDN/api/pri/domain/del \
    --output-dir /tmp --output api-private-domain-del-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domain_id"
    }
EOF
res=$(jq . /tmp/api-private-domain-del-0)
[[ "$res" = "null" ]] && exit 1

out <<< "/api/pri/domain/del"
out <<< "$res"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri completed"
