#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pub/hello"
rm -f /tmp/api-pub-hello

# ------------------------------------------------------------------------------
# /api/pub/hello
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pub/hello \
    --output-dir /tmp --output api-pub-hello \
    -H "Accept: application/json"
res=$(jq . /tmp/api-pub-hello)
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ "$(echo $res | jq -r .text)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pub/hello"
