#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# this script needs the registration to be completed successfully
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pri started"
rm -f /tmp/api-private-*
rm -f /tmp/kratos-login-*
rm -f /tmp/*.kratos.login

# ------------------------------------------------------------------------------
# /api/pri/hello without authentication
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/hello \
    --output-dir /tmp --output api-private-hello \
    -H "Accept: application/json"
res=$(jq -r .text /tmp/api-private-hello)
[[ "$res" != "hello null" ]] && exit 1

out <<< "/api/pri/hello (no authentication)"
out <<< "  $res"

# ------------------------------------------------------------------------------
# kratos login flow
# ------------------------------------------------------------------------------
cookieJar=$(mktemp --suffix .kratos.login)

curl -ks https://$KRATOS_FQDN/self-service/login/browser \
    --output-dir /tmp --output kratos-login-flow \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
actionUrl=$(jq -r .ui.action /tmp/kratos-login-flow)
csrfToken=$(jq -r \
    '.ui.nodes[] | select(.attributes.name=="csrf_token") | .attributes.value' \
    /tmp/kratos-login-flow)

out <<< "kratos login flow, action URL:"
out <<< "  $actionUrl"
out <<< "kratos login flow, CSRF token:"
out <<< "  $csrfToken"

# ------------------------------------------------------------------------------
# kratos credential
# ------------------------------------------------------------------------------
email=$(grep email /tmp/kratos-credential | cut -d= -f2)
passwd=$(grep passwd /tmp/kratos-credential | cut -d= -f2)

out <<< "kratos credential, email:"
out <<< "  $email"
out <<< "kratos credential, passwd:"
out <<< "  $passwd"

# ------------------------------------------------------------------------------
# kratos login
# ------------------------------------------------------------------------------
curl -ks -X POST "$actionUrl" \
    --output-dir /tmp --output kratos-login-session \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "csrf_token": "$csrfToken",
        "password_identifier": "$email",
        "password": "$passwd",
        "method": "password"
    }
EOF
userId=$(jq -r .session.identity.id /tmp/kratos-login-session)
[[ "$userId" = "null" ]] && exit 1

out <<< "kratos login, user ID:"
out <<< "  $userId"

# ------------------------------------------------------------------------------
# /api/pri/hello with authentication
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/hello \
    --output-dir /tmp --output api-private-hello \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
res=$(jq -r .text /tmp/api-private-hello)
[[ "$res" = "hello null" ]] && exit 1

out <<< "/api/pri/hello (with authentication):"
out <<< "  $res"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri completed"
