#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pri/domain/get"
rm -f /tmp/api-pri-domain-get-*

# ------------------------------------------------------------------------------
# /api/pri/domain/get (exists)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(jq -r .id /tmp/api-pri-domain-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/get \
    --output-dir /tmp --output api-pri-domain-get-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId"
    }
EOF
res=$(jq . /tmp/api-pri-domain-get-0)
out <<< "exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ "$(echo $res | jq -r .id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/get (not exists)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/get \
    --output-dir /tmp --output api-pri-domain-get-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId"
    }
EOF
res=$(jq . /tmp/api-pri-domain-get-1)
out <<< "not exists:"
out <<< "$res"

[[ -n "$res" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/get"
