#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/common

header <<< "/api/pri/domain/disable"
rm -f /tmp/api-pri-domain-disable-*

# ------------------------------------------------------------------------------
# /api/pri/domain/disable (not exists)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/disable \
    --output-dir /tmp --output api-pri-domain-disable-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId"
    }
EOF
res=$(jq . /tmp/api-pri-domain-disable-0)
out <<< "not exists:"
out <<< "$res"

[[ "$(echo $res | jq -r .domainId)" != "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/disable (already exists)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(jq -r .domainId /tmp/api-pri-domain-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/disable \
    --output-dir /tmp --output api-pri-domain-disable-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId"
    }
EOF
res=$(jq . /tmp/api-pri-domain-disable-1)
out <<< "exists:"
out <<< "$res"

[[ "$(echo $res | jq -r .domainId)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/disable"
