#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(pwd)
source $BASEDIR/common

header <<< "Registration started"

rm -f /tmp/kratos-registration-*
[[ -z "$KRATOS_FQDN" ]] && KRATOS_FQDN=kratos.galaxy.corp

# ------------------------------------------------------------------------------
# start flow
# ------------------------------------------------------------------------------
cookieJar=$(mktemp --suffix .kratos)

curl -ks https://$KRATOS_FQDN/self-service/registration/browser \
    --output-dir /tmp --output kratos-registration-flow \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
actionUrl=$(jq -r .ui.action /tmp/kratos-registration-flow)
csrfToken=$(jq -r \
    '.ui.nodes[] | select(.attributes.name=="csrf_token") | .attributes.value' \
    /tmp/kratos-registration-flow)

out <<< "Registration action URL: $actionUrl"
out <<< "Registration CSRF token: $csrfToken"

# ------------------------------------------------------------------------------
# register
# ------------------------------------------------------------------------------
email=user.$(date +%s)@galaxy.corp
passwd=$(openssl rand -base64 12)

curl -ks -X POST "$actionUrl" \
    --output-dir /tmp --output kratos-registration-session \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "csrf_token": "$csrfToken",
        "traits.email": "$email",
        "password": "$passwd",
        "method": "password"
    }
EOF
userId=$(jq -r .identity.id /tmp/kratos-registration-session)
[[ "$userId" = "null" ]] && exit 1

out <<< "Registration user ID: $userId"
out <<< "Registration user email: $email"
out <<< "Registration user passwd: $passwd"

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "Registration completed"
