#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the meeting owner id
[[ -z "$1" ]] && SET1=1 || SET1=$1
# the member (membership owner) id
[[ -z "$2" ]] && SET2=2 || SET2=$2

# ------------------------------------------------------------------------------
# disable an existing member
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-membership-add-byinvite-id-$SET2-1-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET1" "pri" "meeting/member" "disable" \
    "id" "$JSON" 1
