#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get membership list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting-member" "list" \
    "$JSON" 1
