#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get member list (no limit, no offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/member" "list" "id" \
    "$JSON" 1
