#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the meeting owner
[[ -z "$1" ]] && ID1=1 || ID1=$1
[[ -z "$2" ]] && IDX1=1 || IDX1=$2
# the member (membership owner)
[[ -z "$3" ]] && ID2=2 || ID2=$3
[[ -z "$4" ]] && IDX2=1 || IDX2=$4

SERVICE="pri"
CLASS="meeting/member"
ACTION="set/host"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# set as host an existing member
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-membership-add-bycode-new-host-member-of-permanent-id-$ID2-$IDX2-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX1
