#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# set as host a nonexistent member
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$membership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting/member" "set/host" \
    "$JSON" 1
