#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid post
# number value for string field
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": 123,
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting-member" "update" \
    "$JSON" 1
