#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the partner id
[[ -z "$1" ]] && ID1=2 || ID1=$1
# the invite owner id
[[ -z "$2" ]] && ID2=1 || ID2=$2

[[ -z "$3" ]] && IDX=1 || IDX=$3

SERVICE="pri"
CLASS="domain/partnership"
ACTION="add/bycode"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new partnership
# ------------------------------------------------------------------------------
invite_id=$(jq -r ".[0].id" $TMP/api-pri-domain-invite-add-new-id-$ID2-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID2 "pri" "domain/invite" "get" "exist" \
    "id" "$JSON" $IDX

invite_code=$(jq -r ".[0].code" \
    $TMP/api-pri-domain-invite-get-exist-id-$ID2-$IDX-res)
JSON=$(cat <<EOF
{
    "code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
