#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the partner id
[[ -z "$1" ]] && SET1=2 || SET1=$1
# the invite owner id
[[ -z "$2" ]] && SET2=1 || SET2=$2

# ------------------------------------------------------------------------------
# try to add an already existing partnership
# ------------------------------------------------------------------------------
invite_code=$(jq -r ".[0].code" $TMP/api-pri-domain-invite-get-id-$SET2-1-res)
JSON=$(cat <<EOF
{
    "invite_code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET1" "pri" "domain/partnership" \
    "add/bycode" "$JSON" 1
