#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# delete an existing partnership
# ------------------------------------------------------------------------------
partnership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-domain-partnership-add-bycode-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$partnership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "domain/partnership" "del" \
    "id" "$JSON" 1
