#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for a nonexistent partnership
# ------------------------------------------------------------------------------
partnership_id=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$partnership_id"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "domain/partnership" "get" \
    "$JSON" 1
