#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the partner id
[[ -z "$1" ]] && SET1=2 || SET1=$1
# the invite owner id
[[ -z "$2" ]] && SET2=1 || SET2=$2

# ------------------------------------------------------------------------------
# get for an existing invite
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET2-1-res)
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET1" "pri" "domain/partnership" \
    "get/bydomain" "id" "$JSON" 1
