#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain/partnership"
ACTION="get"
TAG="none"

# ------------------------------------------------------------------------------
# get for a nonexistent partnership
# ------------------------------------------------------------------------------
partnership_id=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$partnership_id"
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
