#!/bin/bash
set -e

BASEDIR=$(dirname $0)
source $BASEDIR/../../common

name="$RANDOM.$(date +'%s').mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "auth_attr": {
    }
}
EOF
)

bash $BASEDIR/../../templates/add-ok "pri" "domain" "$JSON" 0
bash $BASEDIR/../../templates/add-error "pri" "domain" "$JSON" 0
