#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "auth_attr": {
    }
}
EOF
)

# ------------------------------------------------------------------------------
# add a new domain
# ------------------------------------------------------------------------------
bash $TEMPLATES/action-member-id "pri" "domain" "add" "$JSON" 0

# ------------------------------------------------------------------------------
# try to add an already existing domain
# ------------------------------------------------------------------------------
bash $TEMPLATES/action-member-error "pri" "domain" "add" "$JSON" 0
