#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain"
ACTION="add"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing domain
# duplicated (identity_id, name)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-domain-get-exist-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "https://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
