#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to add an already existing domain
# duplicated (identity_id, name)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-domain-get-id-1-res)
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "auth_attr": {
    }
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "domain" "add" "$JSON" 1
