#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to add a new domain with invalid auth_type
# ------------------------------------------------------------------------------
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "UNKNOWN",
    "auth_attr": {
    }
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "domain" "add" "$JSON" 1
