#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new domains
# ------------------------------------------------------------------------------
for i in $(seq 1 $NUM); do
    name="sub-$(date +'%s')-$i-$RANDOM.mydomain.corp"
    JSON=$(cat <<EOF
    {
        "name": "$name",
        "auth_type": "none",
        "domain_attr": {
            "url": "https://meet.jit.si"
        }
    }
EOF
)

    bash $TEMPLATES/action-member-attr "$SET" "pri" "domain" "add" "id" \
        "$JSON" $i
done
