#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain"
ACTION="add"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new domain
# ------------------------------------------------------------------------------
name="sub-$(date +'%s')-$IDX-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "https://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
