#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new domain with invalid auth_type
# ------------------------------------------------------------------------------
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "UNKNOWN",
    "domain_attr": {
        "url": "https://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "domain" "add" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add a new domain with invalid url
# ------------------------------------------------------------------------------
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "ftp://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "domain" "add" "$JSON" 2
