#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add an already existing domain
# duplicated (identity_id, name)
# ------------------------------------------------------------------------------
name=$(jq -r ".[0].name" $TMP/api-pri-domain-get-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "https://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "domain" "add" "$JSON" 1
