#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/domain/del"
rm -f $TMP/api-pri-domain-del-*

cookieJar=$(cat $TMP/kratos-login-cookie)

# ------------------------------------------------------------------------------
# /api/pri/domain/del (exists)
# ------------------------------------------------------------------------------
domain_id=$(jq -r .[0].id $TMP/api-pri-domain-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/del \
    --output-dir $TMP --output api-pri-domain-del-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domain_id"
    }
EOF
res=$(jq . $TMP/api-pri-domain-del-0)
out <<< "exists"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/del (not exists)
# ------------------------------------------------------------------------------
domainId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/del \
    --output-dir $TMP --output api-pri-domain-del-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domain_id"
    }
EOF
res=$(jq . $TMP/api-pri-domain-del-1)
out <<< "not exists"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/del"
