#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-0)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# delete an existing domain
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "domain" "del" "$JSON" 0

# ------------------------------------------------------------------------------
# delete a nonexistent domain
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$domain_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "domain" "del" "$JSON" 0
