#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# disable a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$domain_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "domain" "disable" "$JSON" 1
