#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# disable an existing domain
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "domain" "disable" "$JSON" 1

# ------------------------------------------------------------------------------
# disable a nonexistent domain
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$domain_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "domain" "disable" "$JSON" 1
