#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# enable a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$domain_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$ID" "pri" "domain" "enable" "$JSON" 1
