#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# enable a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$domain_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "domain" "enable" "$JSON" 1
