#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/domain/list"
rm -f $TMP/api-pri-domain-list-*

cookieJar=$(cat $TMP/kratos-login-cookie)

# ------------------------------------------------------------------------------
# /api/pri/domain/list (no limit, no offset)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list \
    --output-dir $TMP --output api-pri-domain-list-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
    }
EOF
res=$(jq . $TMP/api-pri-domain-list-0)
out <<< "no limit, no offset:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list (limit 2, no offset)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list \
    --output-dir $TMP --output api-pri-domain-list-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "limit": 2
    }
EOF
res=$(jq . $TMP/api-pri-domain-list-1)
out <<< "limit 2, no offset:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list (limit 2 offset 1)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list \
    --output-dir $TMP --output api-pri-domain-list-2 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "limit": 2,
        "offset": 1
    }
EOF
res=$(jq . $TMP/api-pri-domain-list-2)
out <<< "limit 2 offset 1:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list \
    --output-dir $TMP --output api-pri-domain-list-3 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "offset": 1000000
    }
EOF
res=$(jq . $TMP/api-pri-domain-list-3)
out <<< "limit 2 offset 1000000:"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/list"
