#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/domain/list/enabled"
rm -f /tmp/api-pri-domain-list-enabled-*

cookieJar=$(cat /tmp/kratos-login-cookie)

# ------------------------------------------------------------------------------
# /api/pri/domain/list/enabled (no limit, no offset)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list/enabled \
    --output-dir /tmp --output api-pri-domain-list-enabled-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
    }
EOF
res=$(jq . /tmp/api-pri-domain-list-enabled-0)
out <<< "no limit, no offset:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list/enabled (limit 2, no offset)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list/enabled \
    --output-dir /tmp --output api-pri-domain-list-enabled-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "limit": 2
    }
EOF
res=$(jq . /tmp/api-pri-domain-list-enabled-1)
out <<< "limit 2, no offset:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list/enabled (limit 2 offset 1)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list/enabled \
    --output-dir /tmp --output api-pri-domain-list-enabled-2 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "limit": 2,
        "offset": 1
    }
EOF
res=$(jq . /tmp/api-pri-domain-list-enabled-2)
out <<< "limit 2 offset 1:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/list/enabled (no limit, offset 1000000)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/domain/list/enabled \
    --output-dir /tmp --output api-pri-domain-list-enabled-3 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "offset": 1000000
    }
EOF
res=$(jq . /tmp/api-pri-domain-list-enabled-3)
out <<< "limit 2 offset 1000000:"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/list/enabled"
