#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get domain list (no limit, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "domain" "list" "$JSON" 1
