#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid auth_type
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-1-res)
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "name": "$name",
    "auth_type": "UNKNOWN",
    "domain_attr": {
        "url": "https://meet.jit.si",
        "app_id": "myappid",
        "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "domain" "update" "$JSON" 1

# ------------------------------------------------------------------------------
# try to update with invalid url
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-1-res)
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "ftp://meet.jit.si",
        "app_id": "myappid",
        "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "domain" "update" "$JSON" 2
