#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to update with invalid post
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-1)
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "name": "$name",
    "auth_type": "UNKNOWN",
    "auth_attr": {
       "app_id": "myappid",
       "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "domain" "update" "$JSON" 1
