#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/domain/update"
rm -f /tmp/api-pri-domain-update-*

# ------------------------------------------------------------------------------
# /api/pri/domain/update (valid post)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(jq -r .[0].id /tmp/api-pri-domain-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/update \
    --output-dir /tmp --output api-pri-domain-update-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId",
        "name": "meet.mydomain.corp",
        "auth_type": "token",
        "auth_attr": {
           "app_id": "myappid",
           "app_key": "myappsecret"
        },
        "enabled": true
    }
EOF
res=$(jq . /tmp/api-pri-domain-update-0)
out <<< "valid post:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/domain/update (invalid post)
# ------------------------------------------------------------------------------
cookieJar=$(cat /tmp/kratos-login-cookie)
domainId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/domain/update \
    --output-dir /tmp --output api-pri-domain-update-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$domainId",
        "name": "meet.mydomain.corp",
        "auth_type": "invalid",
        "auth_attr": {
           "app_id": "myappid",
           "app_key": "myappsecret"
        },
        "enabled": true
    }
EOF
res=$(jq . /tmp/api-pri-domain-update-1)
out <<< "invalid post:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/domain/update"
