#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain"
ACTION="update"
TAG="none"

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "id": "$domain_fake",
    "name": "$name",
    "auth_type": "token",
    "domain_attr": {
        "url": "https://meet.jit.si",
        "app_id": "myappid",
        "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
