#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$ID-1-res)
name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "name": "$name",
    "auth_type": "token",
    "auth_attr": {
        "url": "https://meet.jit.si",
        "app_id": "myappid",
        "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-id "$ID" "pri" "domain" "update" "$JSON" 1
