#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-0)
domain_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "name": "meet.mydomain.corp",
    "auth_type": "token",
    "auth_attr": {
       "app_id": "myappid",
       "app_key": "myappsecret"
    }
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "domain" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid post
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
    {
        "id": "$domain_id",
        "name": "meet.mydomain.corp",
        "auth_type": "UNKNOWN",
        "auth_attr": {
           "app_id": "myappid",
           "app_key": "myappsecret"
        }
    }
EOF
)

bash $TEMPLATES/action-member-error "pri" "domain" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
    {
        "id": "$domain_fake",
        "name": "meet.mydomain.corp",
        "auth_type": "token",
        "auth_attr": {
           "app_id": "myappid",
           "app_key": "myappsecret"
        }
    }
EOF
)

bash $TEMPLATES/action-member-empty "pri" "domain" "update" "$JSON" 0
