#!/bin/bash
set -e

BASEDIR=$(dirname $0)
source $BASEDIR/../../common

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-ok-0)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# hidden
# ------------------------------------------------------------------------------
name="meeting-$RANDOM-$(date +'%s')"
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
}
EOF
)
bash $BASEDIR/../../templates/add-ok "pri" "meeting" "$JSON" 0

# ------------------------------------------------------------------------------
# non-hidden
# ------------------------------------------------------------------------------
name="meeting-$RANDOM-$(date +'%s')"
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": false,
    "restricted": false
}
EOF
)
bash $BASEDIR/../../templates/add-ok "pri" "meeting" "$JSON" 1

# ------------------------------------------------------------------------------
# nonexistent room
# ------------------------------------------------------------------------------
name="meeting-$RANDOM-$(date +'%s')"
JSON=$(cat <<EOF
{
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
}
EOF
)
bash $BASEDIR/../../templates/add-error "pri" "meeting" "$JSON" 0
