#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/meeting/add"
rm -f /tmp/api-pri-meeting-add-*

cookieJar=$(cat /tmp/kratos-login-cookie)
room_id=$(jq -r ".[0].id" /tmp/api-pri-room-add-0)
room_fake=$(uuidgen)
name="meeting-$RANDOM-$(date +'%s')"

# ------------------------------------------------------------------------------
# /api/pri/meeting/add (not exists)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/meeting/add \
    --output-dir /tmp --output api-pri-meeting-add-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "room_id": "$room_id",
        "name": "mymeeting",
        "info": "some meeting info",
        "schedule_type": "permenant",
        "schedule_attr": "{}",
        "hidden": true,
        "restricted": false
    }
EOF
res=$(jq . /tmp/api-pri-meeting-add-0)
out <<< "not exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/meeting/add (exists)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/meeting/add \
    --output-dir /tmp --output api-pri-meeting-add-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "room_id": "$room_id",
        "name": "mymeeting",
        "info": "some meeting info",
        "schedule_type": "permenant",
        "schedule_attr": "{}",
        "hidden": true,
        "restricted": false
    }
EOF
res=$(jq . /tmp/api-pri-meeting-add-1)
out <<< "exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/meeting/add (for nonexistent domain)
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pri/meeting/add \
    --output-dir /tmp --output api-pri-meeting-add-2 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "room_id": "$room_fake",
        "name": "mymeeting",
        "info": "some meeting info",
        "schedule_type": "permenant",
        "schedule_attr": "{}",
        "hidden": true,
        "restricted": false
    }
EOF
res=$(jq . /tmp/api-pri-meeting-add-2)
out <<< "for notexistent domain:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/meeting/add"
