#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-ok-0)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# add a hidden meeting
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
}
EOF
)
bash $TEMPLATES/add-ok "pri" "meeting" "$JSON" 0

# ------------------------------------------------------------------------------
# add a non-hidden meeting
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": false,
    "restricted": false
}
EOF
)
bash $TEMPLATES/add-ok "pri" "meeting" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add a meeting for a nonexistent room
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
}
EOF
)
bash $TEMPLATES/add-error "pri" "meeting" "$JSON" 0
