#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# try to add a new meeting for a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false,
    "subscribable": true
}
EOF
)

bash $TEMPLATES/action-member-error "$ID" "pri" "meeting" "add" "$JSON" 1
