#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting"
ACTION="add"
TAG="invalid"
ATTR="id"

# ------------------------------------------------------------------------------
# try to add a new meeting for a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-get-default-0-id-$ID-1-res)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "hidden": true,
    "restricted": false,
    "subscribable": true
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
