#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-0)

# ------------------------------------------------------------------------------
# add many new meetings
# ------------------------------------------------------------------------------
for i in $(seq 1 $NUM); do
    name="meeting-$(date +'%s')-$i-$RANDOM"
    JSON=$(cat <<EOF
    {
        "room_id": "$room_id",
        "name": "$name",
        "info": "some meeting info",
        "schedule_type": "permanent",
        "schedule_attr": "{}",
        "hidden": false,
        "restricted": true
    }
EOF
)

    bash $TEMPLATES/action-member-id "pri" "meeting" "add" "$JSON" 0
done
