#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# meeting
[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX1=1 || IDX1=$2
# room
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="meeting"
ACTION="add"
TAG="new-permanent"
ATTR="id"

# ------------------------------------------------------------------------------
# add new meeting
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-get-default-0-id-$ID-1-res)
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-new-id-$ID-$IDX2-res)
name="meeting-$(date +'%s')-$IDX1-$RANDOM"
schedule_type="permanent"
hidden=false
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "$schedule_type",
    "hidden": $hidden,
    "restricted": true,
    "subscribable": true
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX1
