#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new meetings
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$SET-1-res)

hidden=false
for i in $(seq 1 $NUM); do
    name="meeting-$(date +'%s')-$i-$RANDOM"
    JSON=$(cat <<EOF
    {
        "room_id": "$room_id",
        "name": "$name",
        "info": "some meeting info",
        "schedule_type": "permanent",
        "schedule_attr": "{}",
        "hidden": $hidden,
        "restricted": true,
        "subscribable": true
    }
EOF
)
    [[ "$hidden" = false ]] && hidden=true || hidden=false

    bash $TEMPLATES/action-member-id "$SET" "pri" "meeting" "add" "$JSON" $i
done
