#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/meeting/del"
rm -f /tmp/api-pri-meeting-del-*

cookieJar=$(cat /tmp/kratos-login-cookie)

# ------------------------------------------------------------------------------
# /api/pri/meeting/del (exists)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r .[0].id /tmp/api-pri-meeting-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/del \
    --output-dir /tmp --output api-pri-meeting-del-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meeting_id"
    }
EOF
res=$(jq . /tmp/api-pri-meeting-del-0)
out <<< "exists"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/meeting/del (not exists)
# ------------------------------------------------------------------------------
meetingId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/del \
    --output-dir /tmp --output api-pri-meeting-del-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meeting_id"
    }
EOF
res=$(jq . /tmp/api-pri-meeting-del-1)
out <<< "not exists"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/meeting/del"
