#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting"
ACTION="del"
TAG="exist-scheduled"
ATTR="id"

# ------------------------------------------------------------------------------
# delete an existing scheduled meeting
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-scheduled-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
