#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1)
meeting_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# enable an existing meeting
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "meeting" "enable" "$JSON" 1

# ------------------------------------------------------------------------------
# enable a nonexistent meeting
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "meeting" "enable" "$JSON" 1
