#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# enable a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting" "enable" "$JSON" 1
