#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/meeting/enable"
rm -f /tmp/api-pri-meeting-enable-*

cookieJar=$(cat /tmp/kratos-login-cookie)

# ------------------------------------------------------------------------------
# /api/pri/meeting/enable (exists)
# ------------------------------------------------------------------------------
meetingId=$(jq -r .[0].id /tmp/api-pri-meeting-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/enable \
    --output-dir /tmp --output api-pri-meeting-enable-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meetingId"
    }
EOF
res=$(jq . /tmp/api-pri-meeting-enable-0)
out <<< "exists:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/meeting/enable (not exists)
# ------------------------------------------------------------------------------
meetingId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/enable \
    --output-dir /tmp --output api-pri-meeting-enable-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meetingId"
    }
EOF
res=$(jq . /tmp/api-pri-meeting-enable-1)
out <<< "not exists:"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/meeting/enable"
