#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=2 || SET=$1

# ------------------------------------------------------------------------------
# get link bymembership for a nonexistent membership
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$membership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting" \
    "get/link/bymembership" "$JSON" 1
