#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get for a nonexistent meeting
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "meeting" "get" "$JSON" 1
