#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting"
ACTION="get/link/bymembership"
TAG="exist-host-member-of-scheduled"
ATTR="url"

# ------------------------------------------------------------------------------
# get link bymembership for an existing membership (host member of scheduled)
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-membership-add-bycode-new-host-member-of-scheduled-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
