#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get meeting list (limit 2, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-id "$SET" "pri" "meeting" "list" "$JSON" 2
