#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get meeting list (no limit, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting" "list" "id" "$JSON" 1
