#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get meeting list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting" "list" "$JSON" 1
