#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
room_fake=$(uuidgen)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
    {
    "id": "$meeting_fake",
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "hidden": true,
    "restricted": false,
    "subscribable": true
    }
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting" "update" "$JSON" 1
