#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting"
ACTION="update"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to update with invalid post
# schedule_type is incorrect in the example
# ------------------------------------------------------------------------------
meeting_fake=$(uuidgen)
room_fake=$(uuidgen)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
    {
    "id": "$meeting_fake",
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "UNKNOWN",
    "hidden": true,
    "restricted": false,
    "subscribable": true
    }
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
