#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-get-id-$SET-1-res)
room_id=$(jq -r ".[0].room_id" $TMP/api-pri-meeting-get-id-$SET-1-res)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "hidden": true,
    "restricted": false,
    "subscribable": true
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting" "update" "id" \
    "$JSON" 1
