#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-0)
room_fake=$(uuidgen)
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-0)
meeting_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "meeting" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid post
# schedule_type is incorrect in the example
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
    {
    "id": "$meeting_fake",
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "UNKNOWN",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
    }
EOF
)

bash $TEMPLATES/action-member-error "pri" "meeting" "update" "$JSON" 0

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
    {
    "id": "$meeting_fake",
    "room_id": "$room_fake",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false
    }
EOF
)

bash $TEMPLATES/action-member-empty "pri" "meeting" "update" "$JSON" 0
