#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../common

header <<< "/api/pri/meeting/update"
rm -f $TMP/api-pri-meeting-update-*

cookieJar=$(cat $TMP/kratos-login-cookie)
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-0)
room_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# /api/pri/meeting/update (valid post)
# ------------------------------------------------------------------------------
meetingId=$(jq -r .[0].id $TMP/api-pri-meeting-add-0)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/update \
    --output-dir $TMP --output api-pri-meeting-update-0 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meetingId",
        "room_id": "$room_id",
        "name": "mymeeting",
        "info": "some meeting info",
        "schedule_type": "permanent",
        "schedule_attr": "{}",
        "hidden": true,
        "restricted": false
    }
EOF
res=$(jq . $TMP/api-pri-meeting-update-0)
out <<< "valid post:"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].id)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].id)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# /api/pri/meeting/update (invalid post)
# ------------------------------------------------------------------------------
meetingId=$(uuidgen)

curl -ks -X POST https://$APP_FQDN/api/pri/meeting/update \
    --output-dir $TMP --output api-pri-meeting-update-1 \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data @- << EOF
    {
        "id": "$meetingId",
        "room_id": "$room_fake",
        "name": "mymeeting",
        "info": "some meeting info",
        "schedule_type": "UNKNOWN",
        "schedule_attr": "{}",
        "hidden": true,
        "restricted": false
    }
EOF
res=$(jq . $TMP/api-pri-meeting-update-1)
out <<< "invalid post:"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pri/meeting/update"
