#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-get-id-1-res)
room_id=$(jq -r ".[0].room_id" $TMP/api-pri-meeting-get-id-1-res)
name="meeting-$(date +'%s')-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$meeting_id",
    "room_id": "$room_id",
    "name": "$name",
    "info": "some meeting info",
    "schedule_type": "permanent",
    "schedule_attr": "{}",
    "hidden": true,
    "restricted": false,
    "subscribable": true
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "meeting" "update" "$JSON" 1
