#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to accept a nonexistent request
# ------------------------------------------------------------------------------
request_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_fake"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/request" "accept" \
    "$JSON" 1
