#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new request for a nonexistent meeting
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
meeting_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_fake"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/request" "add" \
    "$JSON" 2
