#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID1=2 || ID1=$1
[[ -z "$2" ]] && IDX1=1 || IDX1=$2
# the meeting owner
[[ -z "$3" ]] && ID2=1 || ID2=$3
[[ -z "$4" ]] && IDX2=1 || IDX2=$4

SERVICE="pri"
CLASS="meeting/request"
ACTION="add"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new request
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-get-default-0-id-$ID1-1-res)
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-$ID2-$IDX2-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX1
