#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="add"
TAG="exist-request"

# ------------------------------------------------------------------------------
# try to add an already existing request
# duplicated (identity_id, meeting_id)
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].profile_id" \
    $TMP/api-pri-meeting-request-get-exist-id-$ID-$IDX-res)
meeting_id=$(jq -r ".[0].meeting_id" \
    $TMP/api-pri-meeting-request-get-exist-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
