#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add an already existing request
# duplicated (identity_id, meeting_id)
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].profile_id" \
    $TMP/api-pri-meeting-request-get-id-$SET-1-res)
meeting_id=$(jq -r ".[0].meeting_id" \
    $TMP/api-pri-meeting-request-get-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/request" "add" \
    "$JSON" 1
