#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="get"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get for an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-request-add-new-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
