#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-request-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "meeting/request" "get" "id" \
    "$JSON" 1
