#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="list"
TAG="limit-offset"
ATTR="id"

# ------------------------------------------------------------------------------
# get request list (limit 2, offset 1)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2,
    "offset": 1
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
