#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the meeting owner
[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="reject"
TAG="none"

# ------------------------------------------------------------------------------
# try to reject a nonexistent request
# ------------------------------------------------------------------------------
request_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
