#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the meeting owner id
[[ -z "$1" ]] && SET1=1 || SET1=$1
# the request owner id
[[ -z "$2" ]] && SET2=2 || SET2=$2

# ------------------------------------------------------------------------------
# reject an existing request
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-request-add-id-$SET2-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET1" "pri" "meeting/request" "reject" \
    "id" "$JSON" 1
