#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid post
# a nonexistent profile in the example
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-request-add-id-$SET-1-res)
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_id",
    "profile_id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "meeting/request" "update" \
    "$JSON" 1
