#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="update"
TAG="none"

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
request_fake=$(uuidgen)
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_fake",
    "profile_id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
