#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" $TMP/api-pri-request-add-id-$SET-1-res)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "request" "update" "id" \
    "$JSON" 1
