#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="update"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-request-add-new-id-$ID-$IDX-res)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-get-default-0-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$request_id",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
