#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the request owner
[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/request"
ACTION="update"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to update with invalid post
# a nonexistent profile in the example
# ------------------------------------------------------------------------------
request_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-request-add-new-id-$ID-$IDX-res)
profile_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$request_id",
    "profile_id": "$profile_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
