#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common


[[ -z "$1" ]] && ID=1 || ID=$1
# contact index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# meeting index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="meeting/member/candidate"
ACTION="add"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing candidate of the meeting
# duplicated (meeting_id, contact_id, join_as)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-$ID-$IDX2-res)
contact_id=$(jq -r ".[$((IDX - 1 ))].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "contact_id": "$contact_id",
    "join_as": "host"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
