#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# contact index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# meeting index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="meeting/member/candidate"
ACTION="add"

# ------------------------------------------------------------------------------
# try to add a new meeting-member-candidate with an invalid meeting
# ------------------------------------------------------------------------------
TAG="invalid-meeting"

meeting_fake=$(uuidgen)
contact_id=$(jq -r ".[$((IDX - 1 ))].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_fake",
    "contact_id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new meeting-member-candidate with an invalid contact
# ------------------------------------------------------------------------------
TAG="invalid-contact"

meeting_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-add-new-permanent-id-$ID-$IDX-res)
contact_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "contact_id": "$contact_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
