#!/usr/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../config
source $BASEDIR/../common

SERVICE=$1
CLASS=$2
CLASS_DASHED=$(echo $CLASS | sed 's~/~-~g')
ACTION=$3
ACTION_DASHED=$(echo $ACTION | sed 's~/~-~g')
TAG=$4
JSON=$5
[[ -z "$6" ]] && IDX=0 || IDX=$6

# ------------------------------------------------------------------------------
# /api/<service>/<class>/<action> -> error
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/$CLASS/$ACTION [$TAG] -> error"
rm -f $TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$TAG-error-$IDX-*

echo "$JSON" >$TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$TAG-error-$IDX-req

curl -ks -X POST https://$GALAXY_FQDN/api/$SERVICE/$CLASS/$ACTION \
    --output-dir $TMP \
    --output api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$TAG-error-$IDX-res \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data "$JSON"
res=$(jq . $TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$TAG-error-$IDX-res)

inp <<< "$(echo $JSON | jq .)"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1
footer <<< "/api/$SERVICE/$CLASS/$ACTION [$TAG] -> error"
