#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

SERVICE=$1
CLASS=$2
ACTION=$3
ACTION_DASHED=$(echo $ACTION | sed 's~/~-~g')
JSON=$4
[[ -z "$5" ]] && NUM=0 || NUM=$5

# ------------------------------------------------------------------------------
# /api/<service>/<class>/<action> -> empty
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/$CLASS/$ACTION -> empty"
rm -f $TMP/api-$SERVICE-$CLASS-$ACTION_DASHED-empty-$NUM

cookieJar=$(cat $TMP/kratos-login-cookie)
curl -ks -X POST https://$APP_FQDN/api/$SERVICE/$CLASS/$ACTION \
    --output-dir $TMP --output api-$SERVICE-$CLASS-$ACTION_DASHED-empty-$NUM \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data "$JSON"
res=$(jq . $TMP/api-$SERVICE-$CLASS-$ACTION_DASHED-empty-$NUM)

inp <<< "$(echo $JSON | jq .)"
out <<< "$res"

[[ "$res" != "[]" ]] && exit 1
footer <<< "/api/$SERVICE/$CLASS/$ACTION -> empty"
