#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

SERVICE=$1
CLASS=$2
ACTION=$3
ACTION_DASHED=$(echo $ACTION | sed 's~/~-~g')
JSON=$4
[[ -z "$5" ]] && NUM=0 || NUM=$5

# ------------------------------------------------------------------------------
# /api/<service>/<class>/<action> -> error
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/$CLASS/$ACTION -> error"
rm -f $TMP/api-$SERVICE-$CLASS-$ACTION_DASHED-error-$NUM

curl -ks -X POST https://$APP_FQDN/api/$SERVICE/$CLASS/$ACTION \
    --output-dir $TMP --output api-$SERVICE-$CLASS-$ACTION_DASHED-error-$NUM \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data "$JSON"
res=$(jq . $TMP/api-$SERVICE-$CLASS-$ACTION_DASHED-error-$NUM)

inp <<< "$(echo $JSON | jq .)"
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1
footer <<< "/api/$SERVICE/$CLASS/$ACTION -> error"
