#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../config
source $BASEDIR/../common

SERVICE=$1
CLASS=$2
CLASS_DASHED=$(echo $CLASS | sed 's~/~-~g')
ACTION=$3
ACTION_DASHED=$(echo $ACTION | sed 's~/~-~g')
ATTR=$4
JSON=$5
[[ -z "$6" ]] && IDX=0 || IDX=$6

# ------------------------------------------------------------------------------
# /api/<service>/<class>/<action> -> attr
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/$CLASS/$ACTION -> attr"
rm -f $TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$ATTR-$IDX-*

echo "$JSON" >$TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$ATTR-$IDX-req

curl -ks -X POST https://$APP_FQDN/api/$SERVICE/$CLASS/$ACTION \
    --output-dir $TMP \
    --output api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$ATTR-$IDX-res \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    --data "$JSON"
res=$(jq . $TMP/api-$SERVICE-$CLASS_DASHED-$ACTION_DASHED-$ATTR-$IDX-res)

inp <<< "$(echo $JSON | jq .)"
out <<< "$res"

[[ -z "$(echo $res | jq .[0])" ]] && exit 1
[[ -z "$(echo $res | jq -r .[0].$ATTR)" ]] && exit 1
[[ "$(echo $res | jq -r .[0].$ATTR)" = "null" ]] && exit 1
footer <<< "/api/$SERVICE/$CLASS/$ACTION -> $ATTR"
