#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

ID=$1
SERVICE=$2
[[ -z "$3" ]] && NUM=0 || NUM=$3

# ------------------------------------------------------------------------------
# /api/<service>/hello -> text
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/hello -> text (id: $ID)"
rm -f $TMP/api-$SERVICE-hello-text-$ID-$NUM

cookieJar=$(cat $TMP/kratos-$ID-login-cookie)
curl -ks -X POST https://$APP_FQDN/api/$SERVICE/hello \
    --output-dir $TMP --output api-$SERVICE-hello-text-$ID-$NUM \
    --cookie $cookieJar --cookie-jar $cookieJar \
    -H "Accept: application/json"
res=$(jq . $TMP/api-$SERVICE-hello-text-$ID-$NUM)

out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .text)" ]] && exit 1
[[ "$(echo $res | jq -r .text)" = "hello null" ]] && exit 1
footer <<< "/api/$SERVICE/hello -> text (id: $ID)"
