#!/usr/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../../config
source $BASEDIR/../common

SERVICE=$1
[[ -z "$2" ]] && IDX=0 || IDX=$2

# ------------------------------------------------------------------------------
# /api/<service>/hello -> text
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/hello -> text"
rm -f $TMP/api-$SERVICE-hello-text-$IDX

curl -ks -X POST https://$GALAXY_FQDN/api/$SERVICE/hello \
    --output-dir $TMP --output api-$SERVICE-hello-text-$IDX \
    -H "Accept: application/json"
res=$(jq . $TMP/api-$SERVICE-hello-text-$IDX)

out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .text)" ]] && exit 1
[[ "$(echo $res | jq -r .text)" = "null" ]] && exit 1
footer <<< "/api/$SERVICE/hello -> text"
