#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

SERVICE=$1
[[ -z "$2" ]] && NUM=0 || NUM=$2

# ------------------------------------------------------------------------------
# /api/service/hello -> error
# ------------------------------------------------------------------------------
header <<< "/api/$SERVICE/hello -> error"
rm -f $TMP/api-$SERVICE-hello-error-*

cookieJar=$(cat $TMP/kratos-login-cookie)
curl -ks -X POST https://$APP_FQDN/api/$SERVICE/hello \
    --output-dir $TMP --output api-$SERVICE-hello-error-$NUM \
    -H "Accept: application/json"
res=$(jq . $TMP/api-$SERVICE-hello-error-$NUM)
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .error)" ]] && exit 1
[[ "$(echo $res | jq -r .error)" = "null" ]] && exit 1
footer <<< "/api/$SERVICE/hello -> error"
