#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the partner id
[[ -z "$1" ]] && ID1=2 || ID1=$1
# the invite owner id
[[ -z "$2" ]] && ID2=1 || ID2=$2
[[ -z "$3" ]] && IDX=1 || IDX=$3

SERVICE="pri"
CLASS="room/partnership"
ACTION="add/bycode"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing partnership
# ------------------------------------------------------------------------------
invite_code=$(jq -r ".[0].code" \
    $TMP/api-pri-room-invite-get-exist-id-$ID2-1-res)
JSON=$(cat <<EOF
{
    "invite_code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-error $ID1 $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
