#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new partnership for a nonexistent invite
# ------------------------------------------------------------------------------
invite_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "invite_code": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET" "pri" "room/partnership" \
    "add/bycode" "$JSON" 1
