#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# delete a nonexistent partnership
# ------------------------------------------------------------------------------
partnership_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$partnership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room/partnership" "del" \
    "$JSON" 1
