#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for a nonexistent room
# ------------------------------------------------------------------------------
room_id=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$room_id"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room/partnership" \
    "get/byroom" "$JSON" 1
