#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the partner
[[ -z "$1" ]] && SET=2 || SET=$1

# ------------------------------------------------------------------------------
# get for an existing partnership
# ------------------------------------------------------------------------------
partnership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-room-partnership-add-bycode-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$partnership_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "room/partnership" "get" \
    "id" "$JSON" 1
