#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && IDX=1 || IDX=$1

SERVICE="pub"
CLASS="meeting/schedule"
ACTION="get/bycode"
TAG="none"

# ------------------------------------------------------------------------------
# get bycode for a nonexistent schedule
# ------------------------------------------------------------------------------
code_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "code": "$code_fake"
}
EOF
)

bash $TEMPLATES/action-guest-empty $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
