#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common


[[ -z "$1" ]] && ID=1 || ID=$1
# contact index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# room index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="room/partner/candidate"
ACTION="add"
TAG="exist"

# ------------------------------------------------------------------------------
# try to add an already existing candidate
# duplicated (room_id, contact_id)
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-new-id-$ID-$IDX2-res)
contact_id=$(jq -r ".[$((IDX - 1 ))].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "contact_id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
