#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room/partner/candidate"
ACTION="list/byroom"
TAG="huge-offset"

# ------------------------------------------------------------------------------
# get candidate list by room (no limit, offset 1000000)
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-new-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
