#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the membership owner id
[[ -z "$1" ]] && SET1=2 || SET1=$1
# the invite owner id
[[ -z "$2" ]] && SET2=1 || SET2=$2

# ------------------------------------------------------------------------------
# try to add an already existing membership
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET1-1-res)
code=$(jq -r ".[0].code" $TMP/api-pri-meeting-invite-get-id-$SET2-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "code": "$code"
}
EOF
)

bash $TEMPLATES/action-member-error "$SET1" "pri" "meeting/membership" \
    "add/bycode" "$JSON" 1
