#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=2 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="meeting/membership"
ACTION="add/bycode"
TAG="invalid"
ATTR="id"

# ------------------------------------------------------------------------------
# try to add a new membership for a nonexistent invite
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-get-default-0-id-$ID-1-res)
code_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "code": "$code_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
