#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the membership owner id
[[ -z "$1" ]] && SET1=2 || SET1=$1
# the invite owner id
[[ -z "$2" ]] && SET2=1 || SET2=$2
[[ -z "$3" ]] && NUM=1 || NUM=$3

# ------------------------------------------------------------------------------
# add many new memberships
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET1-1-res)
for i in $(seq 1 $NUM); do
    invite_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-invite-add-id-$SET2-$i-res)
    JSON=$(cat <<EOF
    {
        "id": "$invite_id"
    }
EOF
)
    bash $TEMPLATES/action-member-attr "$SET2" "pri" "meeting/invite" \
        "get" "id" "$JSON" $i

    invite_code=$(jq -r ".[0].code" \
                      $TMP/api-pri-meeting-invite-get-id-$SET2-$i-res)
    JSON=$(cat <<EOF
    {
        "profile_id": "$profile_id",
        "invite_code": "$invite_code"
    }
EOF
)

    bash $TEMPLATES/action-member-attr "$SET1" "pri" "meeting/membership" \
        "add/byinvite" "id" "$JSON" $i
done
