#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

# the membership owner id
[[ -z "$1" ]] && ID1=2 || ID1=$1
# the invite owner id
[[ -z "$2" ]] && ID2=1 || ID2=$2
[[ -z "$3" ]] && IDX=1 || IDX=$3

SERVICE="pri"
CLASS="meeting/membership"
ACTION="add/bycode"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new membership
# ------------------------------------------------------------------------------
invite_id=$(jq -r ".[0].id" \
    $TMP/api-pri-meeting-invite-add-new-host-member-id-$ID2-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)
bash $TEMPLATES/action-member-attr $ID2 "pri" "meeting/invite" "get" "exist" \
    "id" "$JSON" $IDX

code=$(jq -r ".[0].code" $TMP/api-pri-meeting-invite-get-exist-id-$ID2-$IDX-res)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-new-id-$ID1-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "code": "$code"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID1 $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
