#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$membership_fake",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "meeting/membership" \
    "update" "$JSON" 1
