#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

# ------------------------------------------------------------------------------
# add many new memberships
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1)
for i in $(seq 1 $NUM); do
    (( idx = i - 1 )) || true

    invite_code=$(jq -r ".[$idx].code" $TMP/api-pri-invite-list-id-1)
    JSON=$(cat <<EOF
    {
        "profile_id": "$profile_id",
        "invite_code": "$invite_code"
    }
EOF
)

    bash $TEMPLATES/action-member-id "pri" "membership" "add/byinvite" \
        "$JSON" $i
done
