#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1)
profile_fake=$(uuidgen)
invite_code=$(jq -r ".[0].code" $TMP/api-pri-invite-list-id-1)
invite_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# add a new membership
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "invite_code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "membership" "add/byinvite" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add an already existing membership
# ------------------------------------------------------------------------------
bash $TEMPLATES/action-member-error "pri" "membership" "add/byinvite" "$JSON" 1

# ------------------------------------------------------------------------------
# try to add a new membership for a nonexistent invite
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "invite_code": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "membership" "add/byinvite" "$JSON" 1
