#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# add a new membership
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1)
invite_code=$(jq -r ".[0].code" $TMP/api-pri-invite-list-id-1)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "invite_code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "membership" "add/byinvite" "$JSON" 1
