#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

# ------------------------------------------------------------------------------
# add many new memberships
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1-res)
for i in $(seq 1 $NUM); do
    invite_id=$(jq -r ".[0].id" $TMP/api-pri-invite-add-id-$i-res)
    JSON=$(cat <<EOF
    {
        "id": "$invite_id"
    }
EOF
)
    bash $TEMPLATES/action-member-id "pri" "invite" "get" "$JSON" $i

    invite_code=$(jq -r ".[0].code" $TMP/api-pri-invite-get-id-$i-res)
    JSON=$(cat <<EOF
    {
        "profile_id": "$profile_id",
        "invite_code": "$invite_code"
    }
EOF
)

    bash $TEMPLATES/action-member-id "pri" "membership" "add/byinvite" \
        "$JSON" $i
done
