#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to add an already existing membership
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].profile_id" $TMP/api-pri-invite-add-id-1-res)
invite_code=$(jq -r ".[0].code" $TMP/api-pri-invite-get-id-1-res)
JSON=$(cat <<EOF
{
    "profile_id": "$profile_id",
    "invite_code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "membership" "add/byinvite" "$JSON" 1
