#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

membership_id=$(jq -r ".[0].id" $TMP/api-pri-membership-add-byinvite-id-1)
membership_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# delete an existing membership
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "membership" "del" "$JSON" 1

# ------------------------------------------------------------------------------
# delete a nonexistent membership
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$membership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "membership" "del" "$JSON" 1
