#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get for an existing membership
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" $TMP/api-pri-membership-add-byinvite-id-1)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "membership" "get" "$JSON" 1
