#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get membership list (no limit, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
}
EOF
)

bash $TEMPLATES/action-member-id "$SET" "pri" "membership" "list" "$JSON" 1
