#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$membership_fake",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-empty "$ID" "pri" "membership" "update" "$JSON" 1
