#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# try to update with invalid post
# number value for string field
# ------------------------------------------------------------------------------
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1-res)
JSON=$(cat <<EOF
{
    "id": 123,
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "membership" "update" "$JSON" 1
