#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

membership_id=$(jq -r ".[0].id" $TMP/api-pri-membership-add-byinvite-id-1)
membership_fake=$(uuidgen)
profile_id=$(jq -r ".[0].id" $TMP/api-pri-profile-add-id-1)

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$membership_id",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "membership" "update" "$JSON" 1

# ------------------------------------------------------------------------------
# try to update with invalid post
# number value for string field
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": 123
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "membership" "update" "$JSON" 1

# ------------------------------------------------------------------------------
# try to update with invalid criteria
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$membership_fake",
    "profile_id": "$profile_id"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "membership" "update" "$JSON" 1
