#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# this works only in trusted network
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)

bash $BASEDIR/../templates/hello-unsecure "adm"
