#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# convert contact ID to array index
[[ -z "$2" ]] && IDX=0 || IDX=$(($2 - 1 ))
# domain index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="domain/partner/candidate"
ACTION="add"

# ------------------------------------------------------------------------------
# try to add a new domain-partner-candidate with an invalid domain
# ------------------------------------------------------------------------------
TAG="invalid-domain"

domain_fake=$(uuidgen)
contact_id=$(jq -r ".[$IDX].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake",
    "contact_id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new domain-partner-candidate with an invalid contact
# ------------------------------------------------------------------------------
TAG="invalid-contact"

domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-new-id-$ID-$IDX2-res)
contact_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "contact_id": "$contact_fake"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
