#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# contact index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# domain index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="domain/partner/candidate"
ACTION="add"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new candidate
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-new-id-$ID-$IDX2-res)
contact_id=$(jq -r ".[0].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_id",
    "contact_id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
