#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain/partner/candidate"
ACTION="add"

# ------------------------------------------------------------------------------
# try to add a new domain-partner-candidate with invalid auth_type
# ------------------------------------------------------------------------------
TAG="invalid-auth"

name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "UNKNOWN",
    "domain_attr": {
        "url": "https://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to add a new domain with invalid url
# ------------------------------------------------------------------------------
TAG="invalid-url"

name="sub-$(date +'%s')-$RANDOM.mydomain.corp"
JSON=$(cat <<EOF
{
    "name": "$name",
    "auth_type": "none",
    "domain_attr": {
        "url": "ftp://meet.jit.si"
    }
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
