#!/bin/bash
set -e

REMOTE="https://github.com/emrahcom/galaxy.git"
LOCAL="/tmp/galaxy"
UI="$LOCAL/machines/eb-app-ui/home/ui"
APP="$UI/galaxy-dev"

# get KRATOS FQDN
[[ -z "$KRATOS_FQDN" ]] && \
    KRATOS_FQDN=$(ack KRATOS /home/ui/galaxy-dev/src/lib/config.ts | \
                 cut -d'"' -f2 | cut -d '/' -f3)
if [[ -z "$KRATOS_FQDN" ]]; then
    echo "error: KRATOS_FQDN is not found"
    exit 1
else
   echo "KRATOS_FQDN: $KRATOS_FQDN"
fi

# get APP FQDN
[[ -z "$APP_FQDN" ]] && \
    APP_FQDN=$(ack APP /home/ui/galaxy-dev/src/lib/config.ts | \
              cut -d'"' -f2 | cut -d '/' -f3)
if [[ -z "$APP_FQDN" ]]; then
    echo "error: APP_FQDN is not found"
    exit 1
else
   echo "APP_FQDN: $APP_FQDN"
fi

# clone
rm -rf $LOCAL
git clone --depth=1 $REMOTE $LOCAL

sed -i "s/___KRATOS_FQDN___/$KRATOS_FQDN/" $APP/src/lib/config.ts
sed -i "s/___APP_FQDN___/$APP_FQDN/" $APP/src/lib/config.ts
cat $APP/src/lib/config.ts

# update app
rm -rf /tmp/galaxy-dev.old
mv /home/ui/galaxy-dev /tmp/galaxy-dev.old
mv $APP /home/ui/

# node modules
[[ -d "/tmp/galaxy-dev.old/node_modules" ]] && \
    cp -arp /tmp/galaxy-dev.old/node_modules /home/ui/galaxy-dev/
cd /home/ui/galaxy-dev
npm install

# update this script
cp $UI/update-galaxy-dev /home/ui/
