#!/bin/bash
set -e

REMOTE="https://github.com/emrahcom/galaxy.git"
LOCAL="/tmp/galaxy"
UI="$LOCAL/machines/eb-app-ui/home/ui"
APP="$UI/galaxy-dev"

# get ROOT FQDN
[[ -z "$ROOT_FQDN" ]] && \
    ROOT_FQDN=$(ack "^export const ROOT =" \
                  /home/ui/galaxy-dev/src/lib/config.ts | \
                  cut -d'"' -f2 | cut -d '/' -f3)
if [[ -z "$ROOT_FQDN" ]]; then
    echo "error: ROOT_FQDN is not found"
    exit 1
else
   echo "ROOT_FQDN: $ROOT_FQDN"
fi

# get KRATOS FQDN
[[ -z "$KRATOS_FQDN" ]] && \
    KRATOS_FQDN=$(ack "^export const KRATOS =" \
                  /home/ui/galaxy-dev/src/lib/config.ts | \
                  cut -d'"' -f2 | cut -d '/' -f3)
if [[ -z "$KRATOS_FQDN" ]]; then
    echo "error: KRATOS_FQDN is not found"
    exit 1
else
   echo "KRATOS_FQDN: $KRATOS_FQDN"
fi

# clone
rm -rf $LOCAL
git clone --depth=1 $REMOTE $LOCAL

sed -i "s/___ROOT_FQDN___/$ROOT_FQDN/" $APP/src/lib/config.ts
sed -i "s/___KRATOS_FQDN___/$KRATOS_FQDN/" $APP/src/lib/config.ts
cat $APP/src/lib/config.ts

# upgrade app
rm -rf /tmp/galaxy-dev.old
mv /home/ui/galaxy-dev /tmp/galaxy-dev.old
cp -arp $APP /home/ui/

# node modules
[[ -d "/tmp/galaxy-dev.old/node_modules" ]] && \
    cp -arp /tmp/galaxy-dev.old/node_modules /home/ui/galaxy-dev/
cd /home/ui/galaxy-dev
npm install
#npm upgrade

# upgrade this script
cp $UI/upgrade-galaxy-dev /home/ui/
