#!/usr/bin/bash
set -e

REMOTE="https://github.com/emrahcom/galaxy.git"
[[ -n "$BRANCH" ]] || BRANCH="main"
LOCAL="/tmp/galaxy"
UI="$LOCAL/machines/eb-app-ui/home/ui"
APP="$UI/galaxy-dev"

# clone
cat <<EOF

BRANCH: $BRANCH

EOF

rm -rf $LOCAL
git clone --depth=1 --branch $BRANCH $REMOTE $LOCAL

# upgrade this script
cp $UI/upgrade-galaxy-dev /home/ui/

# upgrade app
rm -rf /tmp/galaxy-dev.old
mv /home/ui/galaxy-dev /tmp/galaxy-dev.old
cp -arp $APP /home/ui/

# node modules
[[ -d "/tmp/galaxy-dev.old/node_modules" ]] && \
    cp -arp /tmp/galaxy-dev.old/node_modules /home/ui/galaxy-dev/
cd /home/ui/galaxy-dev
yarn install

# linter
yarn run check
yarn run lint

# warning
cat <<EOF

DONT FORGET TO BUILD THE APPLICATION

  cd /home/ui/galaxy-dev
  yarn run build
EOF
