#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get partner list (no limit, no offset)
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "domain/partner" \
    "list/bydomain" "id" "$JSON" 1
