#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain/partner"
ACTION="list/bydomain"
TAG="nolimit-nooffset"
ATTR="id"

# ------------------------------------------------------------------------------
# get partner list (no limit, no offset)
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-new-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
