#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# invite index
[[ -z "$2" ]] && IDX=1 || IDX=$2
# room index
[[ -z "$3" ]] && IDX2=1 || IDX2=$3

SERVICE="pri"
CLASS="room/invite"
ACTION="add"
TAG="new"
ATTR="id"

# ------------------------------------------------------------------------------
# add new invite
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-new-id-$ID-$IDX2-res)
JSON=$(cat <<EOF
{
    "room_id": "$room_id",
    "name": "invite-$RANDOM"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
