#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new invite for a nonexistent room
# ------------------------------------------------------------------------------
room_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "room_id": "$room_fake",
    "name": "invite-$RANDOM"
}
EOF
)
bash $TEMPLATES/action-member-error "$SET" "pri" "room/invite" "add" "$JSON" 1
