#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room/invite"
ACTION="disable"
TAG="none"

# ------------------------------------------------------------------------------
# disable a nonexistent invite
# ------------------------------------------------------------------------------
invite_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
