#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get for a nonexistent invite
# ------------------------------------------------------------------------------
invite_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room/invite" "get" "$JSON" 1
