#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="room/invite"
ACTION="get/bycode"
TAG="none"

# ------------------------------------------------------------------------------
# get by code for an nonexistent invite
# ------------------------------------------------------------------------------
invite_code=$(uuidgen)
JSON=$(cat <<EOF
{
    "code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
