#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get by code for an nonexistent invite
# ------------------------------------------------------------------------------
invite_code=$(uuidgen)
JSON=$(cat <<EOF
{
    "code": "$invite_code"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room/invite" "get/bycode" \
    "$JSON" 1
