#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get invite list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
room_id=$(jq -r ".[0].id" $TMP/api-pri-room-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$room_id",
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "room/invite" "list/byroom" \
    "$JSON" 1
