#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="calendar"
ACTION="list/bymonth"
TAG="invalid"

# ------------------------------------------------------------------------------
# get calendar events (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
today=$(date +'%Y-%m-%d')
JSON=$(cat <<EOF
{
    "value": "$today",
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# get calendar events (invalid date)
# ------------------------------------------------------------------------------
today=$(date +'%Y%m%d')
JSON=$(cat <<EOF
{
    "value": "$today"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# get calendar events (missing value)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "novalue": "2024-01-01"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
