#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="calendar"
ACTION="list/bymonth"
TAG="huge-offset"

# ------------------------------------------------------------------------------
# get calendar events (no limit, offset 1000000)
# ------------------------------------------------------------------------------
today=$(date +'%Y-%m-%d')
JSON=$(cat <<EOF
{
    "value": "$today",
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
