#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="calendar"
ACTION="list/bymonth"
TAG="nolimit-nooffset"
ATTR="id"

# ------------------------------------------------------------------------------
# get calendar events (no limit, no offset)
# ------------------------------------------------------------------------------
today=$(date +'%Y-%m-%d')
JSON=$(cat <<EOF
{
    "value": "$today"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
