version: v1.3.1

dsn: "postgres://kratos:___DB_PASSWD___@eb-postgres:5432/kratos?\
      sslmode=disable&max_conns=20&max_idle_conns=4"

serve:
  public:
    base_url: https://___KRATOS_FQDN___/
    cors:
      enabled: true
      allowed_origins:
        - https://___APP_FQDN___
  admin:
    base_url: https://___KRATOS_FQDN___:4434/

selfservice:
  default_browser_return_url: https://___APP_FQDN___/
  allowed_return_urls:
    - https://___APP_FQDN___

  methods:
    password:
      enabled: true
      config:
        identifier_similarity_check_enabled: true
        haveibeenpwned_enabled: false
        min_password_length: 8
    totp:
      enabled: true
      config:
        issuer: ___KRATOS_TOTP_ISSUER___
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
      passwordless_enabled: true

  flows:
    error:
      ui_url: https://___APP_FQDN___/id/error

    settings:
      ui_url: https://___APP_FQDN___/id/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://___APP_FQDN___/id/recovery
      use: code
      after:
        default_browser_return_url: https://___APP_FQDN___/pri

    verification:
      enabled: true
      ui_url: https://___APP_FQDN___/id/verification
      use: code
      after:
        default_browser_return_url: https://___APP_FQDN___/pri

    logout:
      after:
        default_browser_return_url: https://___APP_FQDN___

    login:
      ui_url: https://___APP_FQDN___/id/login
      lifespan: 10m
      style: identifier_first
      after:
        password:
          default_browser_return_url: https://___APP_FQDN___/pri
        code:
          default_browser_return_url: https://___APP_FQDN___/pri

    registration:
      enabled: true
      lifespan: 10m
      ui_url: https://___APP_FQDN___/id/registration
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://eb-app-api:8000/api/adm/hello
              method: POST
              body: file:///home/kratos/jsonnet/empty.jsonnet
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://eb-app-api:8000/api/adm/identity/add
                method: POST
                body: file:///home/kratos/jsonnet/identity.jsonnet
            - hook: session
            - hook: show_verification_ui
        code:
          hooks:
            - hook: web_hook
              config:
                url: http://eb-app-api:8000/api/adm/identity/add
                method: POST
                body: file:///home/kratos/jsonnet/identity.jsonnet
            - hook: session

log:
  level: warning
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - ___COOKIE_SECRET___
  cipher:
    - ___CIPHER_SECRET___

ciphers:
  algorithm: xchacha20-poly1305

cookies:
  domain: ___BASE_DOMAIN___
  path: /
  same_site: Strict

session:
  lifespan: 720h
  cookie:
    domain: ___BASE_DOMAIN___
    path: /
    same_site: Strict
    persistent: true

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: schema_v0
  schemas:
    - id: schema_v0
      url: file:///home/kratos/config/identity.schema.v0.json

courier:
  smtp:
    connection_uri: ___KRATOS_SMTP_CONNECTION_URI___
    from_address: ___KRATOS_SMTP_FROM_ADDRESS___
