identity:
  schemas:
    - id: default
      url: file:///home/kratos/config/identity.schema.json

  default_schema_id: default

dsn: "postgres://kratos:___DB_PASSWD___@eb-postgres:5432/kratos?\
      sslmode=disable&max_conns=20&max_idle_conns=4"

selfservice:
  default_browser_return_url: https://___APP_FQDN___/

  flows:
    logout:
      after:
        default_browser_return_url: https://___APP_FQDN___/id/login

    registration:
      ui_url: https://___APP_FQDN___/id/registration
      lifespan: 1h
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://eb-app-api:8000/api/adm/identity/add
                method: POST
                body: /home/kratos/jsonnet/identity.jsonnet
            - hook: session
          default_browser_return_url: https://___APP_FQDN___/id/welcome
      enabled: true

    login:
      ui_url: https://___APP_FQDN___/id/login
      lifespan: 1h
      after:
        password:
          default_browser_return_url: https://___APP_FQDN___/id/welcome

    verification:
      ui_url: https://___APP_FQDN___/id/verification
      lifespan: 1h
      after:
        default_browser_return_url: https://___APP_FQDN___/id/welcome
      enabled: true

    recovery:
      ui_url: https://___APP_FQDN___/id/recovery
      lifespan: 1h
      enabled: true

    error:
      ui_url: https://___APP_FQDN___/id/error

    settings:
      ui_url: https://___APP_FQDN___/id/settings
      lifespan: 1h
      privileged_session_max_age: 1h

  methods:
    password:
      config:
        identifier_similarity_check_enabled: false
      enabled: true

  allowed_return_urls:
    - https://___APP_FQDN___

serve:
  public:
    base_url: https://___KRATOS_FQDN___/
    cors:
      allowed_origins:
        - https://___APP_FQDN___
      allowed_methods:
        - POST
      enabled: true

  admin:
    base_url: https://___KRATOS_FQDN___:4434/

log:
  leak_sensitive_values: true
  format: text
  level: warning

secrets:
  cookie:
    - ___COOKIE_SECRET___
  cipher:
    - ___CIPHER_SECRET___

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

ciphers:
  algorithm: xchacha20-poly1305

cookies:
  domain: ___BASE_DOMAIN___
  path: /
  same_site: Strict

session:
  lifespan: 720h
  cookie:
    domain: ___BASE_DOMAIN___
    path: /
    same_site: Strict
    persistent: true

version: v0.9.0-alpha.2

courier:
  smtp:
    connection_uri: smtps://username:password@eb-mailslurper:1025/?skip_ssl_verify=true
    from_address: no-reply@___APP_FQDN___
