#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="contact"
ACTION="get"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get for an existing contact
# ------------------------------------------------------------------------------
contact_id=$(jq -r ".[0].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
