#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
# convert contact ID to array index
[[ -z "$2" ]] && IDX=0 || IDX=$(($2 - 1 ))

SERVICE="pri"
CLASS="contact"
ACTION="get"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# get for an existing contact
# ------------------------------------------------------------------------------
contact_id=$(jq -r ".[$IDX].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
JSON=$(cat <<EOF
{
    "id": "$contact_id"
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
