#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="contact"
ACTION="update"
TAG="invalid"

# ------------------------------------------------------------------------------
# try to update with invalid post
# name is missing in the example
# ------------------------------------------------------------------------------
contact_id=$(jq -r ".[0].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-$IDX-res)
JSON=$(cat <<EOF
{
    "id": "$domain_id"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
