#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="contact"
ACTION="update"
TAG="exist"
ATTR="id"

# ------------------------------------------------------------------------------
# update with valid post
# ------------------------------------------------------------------------------
contact_id=$(jq -r ".[$((IDX - 1))].id" \
    $TMP/api-pri-contact-list-nolimit-nooffset-id-$ID-1-res)
name="name-$RANDOM"
JSON=$(cat <<EOF
{
    "id": "$contact_id",
    "name": "$name",
    "visible": true
}
EOF
)

bash $TEMPLATES/action-member-attr $ID $SERVICE $CLASS $ACTION $TAG $ATTR \
    "$JSON" $IDX
