#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../templates

# ------------------------------------------------------------------------------
# hello to the public api
# ------------------------------------------------------------------------------
bash $TEMPLATES/hello-guest-text "pub"
