#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
BASEDIR=$(dirname $0)
source $BASEDIR/../common

header <<< "/api/pub/hello"
rm -f $TMP/api-pub-hello

# ------------------------------------------------------------------------------
# /api/pub/hello
# ------------------------------------------------------------------------------
curl -ks -X POST https://$APP_FQDN/api/pub/hello \
    --output-dir $TMP --output api-pub-hello \
    -H "Accept: application/json"
res=$(jq . $TMP/api-pub-hello)
out <<< "$res"

[[ -z "$(echo $res | jq .)" ]] && exit 1
[[ -z "$(echo $res | jq -r .text)" ]] && exit 1
[[ "$(echo $res | jq -r .text)" = "null" ]] && exit 1

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
footer <<< "/api/pub/hello"
