#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && NUM=1 || NUM=$1

# ------------------------------------------------------------------------------
# add many new invites
# ------------------------------------------------------------------------------
as_host=true
for i in $(seq 1 $NUM); do
    meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-$i)
    JSON=$(cat <<EOF
    {
        "meeting_id": "$meeting_id",
        "as_host": $as_host
    }
EOF
)
    [[ "$as_host" = false ]] && as_host=true || as_host=false

    bash $TEMPLATES/action-member-id "pri" "invite" "add" "$JSON" $i
done
