#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# add a new invite
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "as_host": false
}
EOF
)
bash $TEMPLATES/action-member-id "pri" "invite" "add" "$JSON" 1
