#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# delete a nonexistent invite
# ------------------------------------------------------------------------------
invite_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$ID" "pri" "invite" "del" "$JSON" 1
