#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# disable a nonexistent invite
# ------------------------------------------------------------------------------
invite_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "invite" "disable" "$JSON" 1
