#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

invite_id=$(jq -r ".[0].id" $TMP/api-pri-invite-add-id-1)
invite_fake=$(uuidgen)

# ------------------------------------------------------------------------------
# disable an existing invite
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "invite" "disable" "$JSON" 1

# ------------------------------------------------------------------------------
# disable a nonexistent invite
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "id": "$invite_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "invite" "disable" "$JSON" 1
