#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get for an existing invite
# ------------------------------------------------------------------------------
invite_id=$(jq -r ".[0].id" $TMP/api-pri-invite-add-id-1)
JSON=$(cat <<EOF
{
    "id": "$invite_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "invite" "get" "$JSON" 1
