#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get invite list (no limit, no offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1-res)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "invite" "list" "$JSON" 1
