#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get invite list (no limit, offset 1000000)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1-res)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "offset": 1000000
}
EOF
)

bash $TEMPLATES/action-member-empty "pri" "invite" "list" "$JSON" 1
