#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get invite list (limit 2, no offset)
# ------------------------------------------------------------------------------
JSON=$(cat <<EOF
{
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "invite" "list" "$JSON" 2
