#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1
[[ -z "$2" ]] && NUM=1 || NUM=$2

# ------------------------------------------------------------------------------
# add many new invites
# ------------------------------------------------------------------------------
for i in $(seq 1 $NUM); do
    domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-$i-res)
    JSON=$(cat <<EOF
    {
        "domain_id": "$domain_id",
        "name": "invite-$RANDOM"
    }
EOF
)

    bash $TEMPLATES/action-member-attr "$SET" "pri" "domain/invite" "add" \
        "id" "$JSON" $i
done
