#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# try to add a new invite for a nonexistent domain
# ------------------------------------------------------------------------------
domain_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "domain_id": "$domain_fake"
}
EOF
)
bash $TEMPLATES/action-member-error "$SET" "pri" "domain/invite" "add" "$JSON" 1
