#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# get invite list (limit 2, no offset)
# ------------------------------------------------------------------------------
domain_id=$(jq -r ".[0].id" $TMP/api-pri-domain-add-id-$SET-1-res)
JSON=$(cat <<EOF
{
    "id": "$domain_id",
    "limit": 2
}
EOF
)

bash $TEMPLATES/action-member-attr "$SET" "pri" "domain/invite" "list" "id" \
    "$JSON" 2
