#!/usr/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../../config
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1
[[ -z "$2" ]] && IDX=1 || IDX=$2

SERVICE="pri"
CLASS="domain/partner/candidacy"
ACTION="accept"

# ------------------------------------------------------------------------------
# try to accept with an invalid post (string Id)
# ------------------------------------------------------------------------------
TAG="invalid-string"

JSON=$(cat <<EOF
{
    "id": "string"
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX

# ------------------------------------------------------------------------------
# try to reject with an invalid post (numeric Id)
# ------------------------------------------------------------------------------
TAG="invalid-number"

JSON=$(cat <<EOF
{
    "id": 987
}
EOF
)

bash $TEMPLATES/action-member-error $ID $SERVICE $CLASS $ACTION $TAG \
    "$JSON" $IDX
