#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && SET=1 || SET=$1

# ------------------------------------------------------------------------------
# disable a nonexistent member
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$membership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$SET" "pri" "member" "disable" "$JSON" 1
