#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# enable an existing member
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" $TMP/api-pri-membership-add-byinvite-id-1-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-id "pri" "member" "enable" "$JSON" 1
