#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# ------------------------------------------------------------------------------
# get member list (invalid limit, invalid offset)
# ------------------------------------------------------------------------------
meeting_id=$(jq -r ".[0].id" $TMP/api-pri-meeting-add-id-1)
JSON=$(cat <<EOF
{
    "meeting_id": "$meeting_id",
    "limit": "INVALID",
    "offset": "INVALID"
}
EOF
)

bash $TEMPLATES/action-member-error "pri" "member" "list" "$JSON" 1
