#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

# the meeting owner id
[[ -z "$1" ]] && ID1=1 || ID1=$1
# the member (membership owner) id
[[ -z "$2" ]] && ID2=2 || ID2=$2

# ------------------------------------------------------------------------------
# set as guest an existing member
# ------------------------------------------------------------------------------
membership_id=$(jq -r ".[0].id" \
    $TMP/api-pri-membership-add-byinvite-id-$ID2-1-res)
JSON=$(cat <<EOF
{
    "id": "$membership_id"
}
EOF
)

bash $TEMPLATES/action-member-id "$ID1" "pri" "member" "set/guest" "$JSON" 1
