#!/bin/bash
set -e

BASEDIR=$(dirname $0)
TEMPLATES=$BASEDIR/../../templates
source $BASEDIR/../../common

[[ -z "$1" ]] && ID=1 || ID=$1

# ------------------------------------------------------------------------------
# set as host a nonexistent member
# ------------------------------------------------------------------------------
membership_fake=$(uuidgen)
JSON=$(cat <<EOF
{
    "id": "$membership_fake"
}
EOF
)

bash $TEMPLATES/action-member-empty "$ID" "pri" "member" "set/host" "$JSON" 1
